### ISSUE TITLE
setup_iface_single_process.sh Hwaddr is 0

### ISSUE THREAD

**Issue by jiamo** [eunyoung14/mtcp#10]
sudo ./setup_iface_single_process.sh 3

    dpdk0     Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
              inet addr:10.0.0.3  Bcast:10.0.0.255  Mask:255.255.255.0
              inet6 addr: fe80::200:ff:fe00:0/64 Scope:Link
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0
              TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000 
              RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

    dpdk1     Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
              inet addr:10.0.1.3  Bcast:10.0.1.255  Mask:255.255.255.0
              inet6 addr: fe80::200:ff:fe00:0/64 Scope:Link
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0
              TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000 
              RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

So why the hwaddr is setting to 0; and after few seconds, `ifconfig`

    dpdk0     Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet6 addr: fe80::200:ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

    dpdk1     Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet6 addr: fe80::200:ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

The ip was disappear.

**Comment by ajamshed** [comment]
Please make sure whether you have the NetworkManager turned off. The Network Manager tends to
reset the registered interfaces' IP addresses periodically (see README: FAQ #2).

Also, please make sure that you followed all the steps in setting up the mTCP environment (specifically related to driver installation). The H/W address set to 00:00:00:00:00:00 usually means that the driver was not properly loaded.

**Comment by jiamo** [comment]
Thanks .

 My machine is a VmFusion + ubunut + ethernet2.virtualDev= "vmxnet3".

 After disable NetworkManager, the ip work fine. I am not sure the ip should be binded  to the same network in VM Subnet Ip? 

While the H/W address still is 00:00:00:00:00:00 .
Here is the bind tools --status answer:

engine@engine:~/Git/mtcp/dpdk-2.0.0/tools$ ./dpdk_nic_bind.py --status

    Network devices using DPDK-compatible driver
    ============================================
    0000:03:00.0 'VMXNET3 Ethernet Controller' drv=igb_uio unused=
    0000:0b:00.0 'VMXNET3 Ethernet Controller' drv=igb_uio unused=

    Network devices using kernel driver
    ===================================
    0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper)' if=eth2 drv=e1000 unused=igb_uio

**Comment by ajamshed** [comment]
It looks like you are testing mTCP on a virtual machine testbed. Currently, we haven't developed the I/O framework for mTCP that can work on virtualized environment (although it can be extended using dpdk's virtualization support). I suggest that you either (i) update the mTCP I/O module to support virtual machine setup, or (ii) switch to actual machines.
