### ISSUE TITLE
dpdk0 cannot up and epserver output "Checking link statusdone".

### ISSUE THREAD

**Issue by eflyinghi** [eunyoung14/mtcp#100]
I'm testing DPDK and mtcp with Ubuntu14.04 installed in VMWare.

The virtual NIC is "Ethernet controller: Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) (rev 01)", which should be supported by dpdk.  And I could run DPDK examples successfully.

But with mtcp dpdk-16.04, after load igb_uio, I could see dpdk0 interface and I could assign an IP address to it:
dpdk0     Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet addr:10.0.0.4  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::200:ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

But it seemed that it cannot up and ip link show unknown status:
6: dpdk0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

And noticed that MAC address of the NIC showed zero.

Run test epserver, I got "Checking link statusdone"

**Comment by ajamshed** [comment]
Please see if issue #35 helps

**Comment by eflyinghi** [comment]
Have tried the solution in Issue #35 , but it doesn't work yet.

I tried with both "ip link set" and "ifconfig dpdk0 hw enth" to add an MAC for the dpdk0 interface, but "ip link" still showed unknown status even if the mac address was showed correctly.
6: dpdk0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:09:f5:3b brd ff:ff:ff:ff:ff:ff

Tried with epserver then, I still got "Checking link statusdone"

**Comment by ajamshed** [comment]
Hi eflyinghi,

We still need to _officially_ extend mTCP to virtualized environments. I realize that this task has been pending for a while now. I will let you know once the virtualization support is ready. Is there any chance you can switch to non-virtualized environment for the time being.
