### ISSUE TITLE
Lingering connections.

### ISSUE THREAD

**Issue by marqs85** [eunyoung14/mtcp#102]
For some time I've had an issue where a number of inactive connections are left lingering irrespective of tcp_timeout or tcp_timewait values. This typically occurs when a large number (>100k) of connections are established or closed simultaneously, resulting to some packets getting lost. So far I've traced 2 different causes for this:
1. Retransmissions with ACK flag set reset tcp_timeout timer. Such retransmissions include FIN/ACK and SYN/ACK, although in the latter case there is no timer set as connection is not fully established yet (timeouts only after tcp_max_syn_retry retries).
2. It seems that sometimes a half-terminated connection ends into a state where it's neither on tcp_timeout or tcp_timewait list.

I applied a modification where a transmitted ACK does not update timer (is there a reason for that?) and where connection is removed from tcp_timeout list only just before it's added to tcp_timewait list. That seems to fix the issues for me so I added a pull request for you to review.

**Comment by ajamshed** [comment]
Hi marqs85,

I am a bit pre-occupied with some high priority work (some important deadlines coming up). I will look at your pull requests and get back to you some time next week.

**Comment by ajamshed** [comment]
Hi marqs85,

We had a look at your merge request and it seems that your suggested changes may solve the issue that you are facing in your specific testbed. But it looks like this change may not necessarily fix the underlying unresolved bug in all (general) cases (e.g. moving `RemoveFromTimeoutList()` to `timer.c`). We will conduct a few more tests with higher concurrency rates and let you know whether there is a more appropriate fix to this problem.

Can you please share your test setup details? e.g. client used/server used/concurrency parameters etc.?

Thanks!

**Comment by marqs85** [comment]
Both issues have occurred with 2 servers directly connected to each other, running epserver/epwget with max_concurrency > 100000. For (1) to occur, tcp_timeout and TCP_MAX_RTX should be selected so that in worst case the latter might keep connection alive beyond former, e.g. tcp_timeout=60 and TCP_MAX_RTX=100. Tweaking TCP_MAX_BACKOFF could also help in finding a suitable setup - with previous values some connections could e.g. end up into a state where FIN/ACK gets retransmitted (final ACK was lost) every 40 secs until max_rtx quota is fulfilled.

**Comment by ajamshed** [comment]
Thanks for the information. We will look in to this issue in the coming days.

**Comment by marqs85** [comment]
I started looking into the issue, and found out that mtcp->timeout_list may get corrupted due to 2 threads (master and MTCPRunThread) modifying it concurrently. mtcp->timewait_list probably suffers from same problem, so these should be protected with mutexes.

**Comment by ajamshed** [comment]
Hi marqs85,

I will check your commit in the coming days (I have a busy schedule for the next few days). I went through the mTCP code quickly with Eunyoung and we both could not find any place in the code where the ``timeout_list`` and the ``timewait_list`` are being updated by the app thread. These changes may have resolved the lingering connections issue in your setup, but it seems that the underlying problem lies somewhere else. I will keep on digging this issue as well. Please let us know if you find anything more. :+1:

**Comment by marqs85** [comment]
The issue seems to have been caused by my own patch that added connection to timeout list in CreateTCPStream. The idea behind that was to put non-established connections under some timeout (in addition to TCP_MAX_SYN_RETRY limit which is not applicable in TCP_ST_SYN_RCVD state) since that had been one source of lingering connections (when final ACK in initial 3-way handshake is never received). Closing the issue for now since the changes solve the issue in my setup. Thanks for looking into this.
