### ISSUE TITLE
mTCP usage by multiple applications

### ISSUE THREAD

**Issue by GopinathSadhu** [eunyoung14/mtcp#104]
I was going through design and code of mTCP, during the process I have following quires on mTCP w.rt to multiple application usage.
1) As mTCP is a library, each application has it's own mTCP instance, then how does this solution prevent multiple application listening on same socket port number?
2) When multiple applications listening on their own ports, which module is responsible to route incoming packets(RX flow) to respective mTCP library(As each application has it's own mTCP instance)?

Thank You,
Gopinath.

**Comment by ajamshed** [comment]
Hi Gopinath,

Apologies for late reply.

Ans 1) mTCP application(s) run in [shared-nothing](https://en.wikipedia.org/wiki/Shared_nothing_architecture) model. The traffic splits across multiple cores in a flow-symmetric fashion using RSS via multi-queue NICs and the traffic remains within the same context (mTCP thread) **bottom-up**. You can think of this model as the one you would setup using BSD socket's [REUSEPORT](https://lwn.net/Articles/542629/) option _i.e._ multiple application thread instances bind to the same underlying TCP port. In current implementation, one thread instance can only bind to a single TCP port. 

Ans 2) You should refer to `tcp_in.c: CreateNewFlowHTEntry()` function.

**Comment by GopinathSadhu** [comment]
Dear Ajamshed,
 Thank you for your reply.

I think I have n't communicated well in my previous query.
My question is in the context of using mTCP by multiple application on same network interface.

As per mTCP paper section 3(Design), the statement says like below.
" **Existing user-level packet libraries only allow one application to access an NIC port. Thus, mTCP can only support one application per NIC port**".

As I understand packet I/O is bottle neck in supporting multiple applications as packet I/O is a library which is linked by every application. can this issue can be solved by making packet I/O as a service?

Thank You,
Gopinath.

**Comment by ajamshed** [comment]
It is possible.... with a little bit of hacking inside the mTCP source code. The main issue with the userspace packet I/O drivers is that only one process can have exclusive access to each NIC queue (as you correctly mentioned). This means that you will have to develop an IPC-based mechanism to transfer packets from one (process) address space to another (process) address space. You can probably try memory mapping some shared region to reduce the cost of data migration.

A much more cleaner way will be to use Ethernet flow directors. DPDK has an API in which you can filter packets (with e.g. different TCP ports) to arbitrary NIC queues. In this way, multiple applications can read from NIC queues directly (which also means that packet migration is not needed). I would recommend that you implement this method.

**Comment by uttampawar** [comment]
@ajamshed, Does this mean, number of application can use this interface will be limited by number of queues available on a NIC?

**Comment by ajamshed** [comment]
Yes.
