### ISSUE TITLE
support for latest version of io_engine/kernel 3.x ?

### ISSUE THREAD

**Issue by rohitjoshi** [eunyoung14/mtcp#105]
Any plan to integrate latest version of [io_engine](https://github.com/ANLAB-KAIST/Packet-IO-Engine) which [supports](https://github.com/ANLAB-KAIST/Packet-IO-Engine/issues/15)  Linux kernel 3.x?

**Comment by ajamshed** [comment]
At the moment we don't have plans of upgrading the ioengine driver (for linux versions 3.0 and above). The PSIO engine driver is managed by another team. You can try contacting them: https://github.com/ANLAB-KAIST/Packet-IO-Engine

**Comment by rohitjoshi** [comment]
@ajamshed thanks.  I was able to successfully build latest version of package-io-engine on 2.x kernel but due to some interface changes, mTCP fails to link. Will submit a patch.

**Comment by ajamshed** [comment]
Hi Rohit,

Apologies for the delayed response. I just went through mTCP's psio driver file (`ixgbe_main.c`) and it looks like the missing function should be: `ps_select()`. You may have to patch up the 3.x version of the driver with this function. Also, please verify that the 3.x version, **as it is**, works fine. You may want to run `pspgen` traffic generator (available from anlab GitHub) to see if the driver is running well.
