### ISSUE TITLE
Is mTCP compatible with the latest Linux kernel (4.7) TCP Stack functionality?

### ISSUE THREAD

**Issue by ShahHemalB** [eunyoung14/mtcp#107]

**Comment by ajamshed** [comment]
Not sure I understood your question. Can you please elaborate?

**Comment by ShahHemalB** [comment]
Hi Asim, 

Thanks for your response. I was trying to check whether all the functionality latest kernel TCP stack provide is supported by mTCP too?

**Comment by ajamshed** [comment]
An mTCP client or server will be able to communicate with its peer running linux-4.7 kernel. But mTCP does not implement all features of the modern Linux TCP/IP stack. For example, mTCP has only NewReno implementation as yet. Please refer to our [paper](http://www.ndsl.kaist.edu/~kyoungsoo/papers/mtcp.pdf) and https://github.com/eunyoung14/mtcp/wiki/Supported-Features for more details about the features mTCP supports.
