### ISSUE TITLE
Sending socket buffer full makes mTCP works unexpectedly

### ISSUE THREAD

**Issue by duoh** [eunyoung14/mtcp#110]
Hi authors,

It seems like when the socket buffer is full, it causes TCP shared buffer corruption.
I tried it by increasing and decreasing sndbuf parameter to see if my assumption correct or not.
If sndbuf size is not huge enough to handle a workload, the data sent to an application seems corrupt.

Thanks,
Wiriyang

**Comment by ajamshed** [comment]
Hi Duoh,

There is currently a restriction in the mTCP stack regarding send buffers. It uses static buffers (fixed size) buffers that can only be adjusted using the configuration file. We eventually hope to fix this, but for the moment you will probably have to rely on the config file.

**Comment by duoh** [comment]
Hello,

Thanks for your confirmation.
May I ask one question? What maximum value of sndbuf can be used?

Thanks

**Comment by ajamshed** [comment]
I think the size of sndbuf is kept in a ``size_t`` variable which means that you can theoretically create ``2^32`` bytes worth of sndbuf. But you are most likely going to run out of memory for a value lower than that. FYI: the send buffers are actually being created from a userspace memory manager (``memory_mgt.c``) and the memory management module pre-allocates large memory chunks from heap (based on the set concurrency limits) during mTCP app initialization.

**Comment by duoh** [comment]
Hello,

Thanks for the useful information.
I have a quick question, is the performance of mTCP better than Linux kernel stack when handling long-live connections like HTTP keep-alive?

Thanks,
Wiriyang

**Comment by ajamshed** [comment]
Wiriyang,

We tested mTCP starting from short flow sizes (64B) all the way up to 8KB files. You can view our evaluation results in section 5 of our [paper](http://www.ndsl.kaist.edu/~kyoungsoo/papers/mtcp.pdf). How large is the size of your flow?

**Comment by duoh** [comment]
Hello,
The size is close to your workload. However, my testing flow in a view point of clients is establishing, sending, receiving, sending, receiving and going on. When I tested this scenario, it seems the performance is poorer than using Linux kernel stack. That's why I would like to confirm my test result.

Thanks,
Wiriyang
