### ISSUE TITLE
mTCP lower interface Q

### ISSUE THREAD

**Issue by sakopzon** [eunyoung14/mtcp#111]
Hi I am participating in some academic project at the Technion, and trying to make mTCP work with another driver neither DPDK or PSIO.
We have some virtual network and a virtual software network chip (including it's "driver" which's purpose is similar to the DPDK) which is configured to work with LWIP single threaded user space TCP/IP stack. Our mission is to replace the LWIP with mTCP.
My question is in which source files, or even better, specification files should I start searching to understand the lower mTCP interface for connecting it to another software?
Thank you very much!

**Comment by ajamshed** [comment]
Hi Sakopzon,

I recommend that you go through the following files: ``io_module.c``, ``io_module.h``, ``dpdk_module.c`` (for reference), and ``core.c``.
