### ISSUE TITLE
support for eventfd and eventfd2 system calls

### ISSUE THREAD

**Issue by uttampawar** [eunyoung14/mtcp#112]
Hi,
I was wondering what it would take to add support for eventfd() system call (with non-blocking support) to mtcp stack?

Thanks,
Uttam

**Comment by jimmyt857** [comment]
I can't speak for OP, but I am interested in using mtcp to write a lighter version of libuv. eventfd() is required to allow another thread (running in the same process) to wake up the epoll_wait() call. Is this currently possible, or do I need to modify eventpoll.c as you suggested?

**Comment by ajamshed** [comment]
It is currently not possible. But we do have it in our plans to implement the function. We are happy to merge pull requests if you take up this task.

**Comment by jimmyt857** [comment]
Ok, I might try to figure this out. I'm not familiar with this project though, would you mind pointing me to the main source files to understand the basics, and which ones I'll need to modify?

**Comment by jimmyt857** [comment]
It turns out I'm running on an Amazon EC2 instance which is not compatible with either of the installation methods. However, I've looked through the code and I know which changes to make, and I wouldn't mind writing this anyway. Is there any way I can successfully compile the project?

**Comment by ajamshed** [comment]
The mTCP stack provides support for netmap (``vale`` interface?) module. Even if you set the stack with dpdk driver, it should still compile. May I know where exactly do you face compilation errors? Just FYI, I plan to roll out virtualization support during March. Right now, ``io_module.c``, ``dpdk_module.c`` and ``netmap_module.c`` files may need to be updated to extend mTCP in virtualized environments. Can you get access to physical (non-virtualized) machines? That will ease the development process for now.

**Comment by jimmyt857** [comment]
I could,  but unfortunately I'd have to pay extra for it.   =C

**Comment by uttampawar** [comment]
@ajamshed Sorry, away for a while. Yes, I've made Node.js runtime/framework work with mTCP+DPDK. With a help from my colleague we added 'eventfd()' support (as a hack). But adding that as a supported operation would be useful.

**Comment by ajamshed** [comment]
Glad to hear that you got eventfd() working. I have put that in my TODOs list. I hope I'll be able to get it implemented sooner rather than later. :)
