### ISSUE TITLE
Can I use multiple event poll descriptor?

### ISSUE THREAD

**Issue by GyuminH** [eunyoung14/mtcp#113]
Hi, I have several questions about epoll and multi-threading.

1. Can I use multiple epoll descriptors?
As far as I understand, it isn't possible because mTCP always inserts events into one event poll descriptor which a mtcp structure points to. If so,

2. Using multi-thread socket scheme is a bad idea?
My first idea was using multi-thread socket. So there is a thread only accepting TCP connections, and other threads handle a created flow respectively. Each threads handling flows has a epoll descriptor to check events of the flow. However, it turned out that I cannot use this idea. I guess it is because of question (1). Then

3. What is the way to process a flow in a dedicated thread?

**Comment by ajamshed** [comment]
Hi GyminH,

You are right. A single mtcp_manager structure can only hold 1 ``mtcp_epoll`` descriptor. The mTCP stack is designed to follow a shared-nothing threading model. I would not suggest creating a dedicated thread for flow management tasks. This will lead to resource contention issues (use of locks) that mTCP [paper](http://www.ndsl.kaist.edu/~kyoungsoo/papers/mtcp.pdf) argues against. Is it possible that you reorganize your code so that it uses ``mtcp_epoll_*`` calls?

**Comment by GyuminH** [comment]
Yes, it is possible.

Is resource contention you mentioned contention between an application 
thread and mTCP thread to read and write events from an event poll 
descriptor?

2017-01-18 오후 9:01에 Asim Jamshed 이(가) 쓴 글:

**Comment by ajamshed** [comment]
No. It would be between two application threads (one that does epoll-ing, the other that does flow management). You will have to develop some sort of a communication channel between the two threads that will require serial access (maybe using locks etc.). I would suggest that you should stick with only 1 application thread model.

**Comment by GyuminH** [comment]
What if there are multiple event poll descriptors and application 
threads don't share these descriptors each other? mTCP thread 
distributes events to these descriptors and application thread do 
epoll-* on its own event poll descriptor. I'm not sure it is possible or 
not, but if it is possible then there is no contention between 
application threads. The only contention I guess is between mTCP and 
application threads.
I'm sorry for my ridiculous thoughts.


2017-01-22 오후 6:50에 Asim Jamshed 이(가) 쓴 글:

**Comment by ajamshed** [comment]
I can see your point. You will probably need to do a little bit of hacking in the mTCP core stack. You can probably start by adding support for multiple epoll descriptors in ``mtcp_manager_t``. But do you want to spawn multiple application threads in the same core? Please keep the ["thread context switching per core"](http://stackoverflow.com/questions/5440128/thread-context-switch-vs-process-context-switch) overhead in mind as well.

**Comment by GyuminH** [comment]
Right, I'm also considering the context switching overhead and I can't 
imagine the impact of the overhead.
Anyway, I don't have any plan to modify mTCP core stack yet.

Thanks :)


2017-01-23 오후 12:52에 Asim Jamshed 이(가) 쓴 글:
