### ISSUE TITLE
epoll event queue understandings.

### ISSUE THREAD

**Issue by GopinathSadhu** [eunyoung14/mtcp#114]
I have observed following event queues for poll feature
	a) USR_EVENT_QUEUE, b) USR_SHADOW_EVENT_QUEUE, c) MTCP_EVENT_QUEUE

1) As I understand USR_SHADOW_EVENT_QUEUE is required for 2 cases
  i) To raise epoll event when data present at socket to read/write even before creating epoll socket.
  ii) To invoke epoll again to APP, when APP is not fetching/sending complete data through mtcp_read/mtcp_write in continuous loops.
  I mean following APP code does not make use of USR_SHADOW_EVENT_QUEUE
  mtcp_epoll_wait(MTCP_EPOLLIN, ..)
  for(i = 0->nevents)
  {
        if(event == MTCP_EPOLLIN)
       {
              whle(readbytes>0)
                    mtcp_read(..);
       }
  }
  
2) Why MTCP_EVENT_QUEUE is required? what if MTCPRunThread pushes events to USR_EVENT_QUEUE directly instead of pushing to MTCP_EVENT_QUEUE first and then copying to USR_EVENT_QUEUE.

Please give your opinion about my understandings.

Thank You,
Gopinath.

**Comment by eunyoung14** [comment]
Hi Gopinate, 
We designed so to minimize lock (or context switch) between mtcp thread and application thread, and process the events in a batch. As you understand, user shadow queue and mtcp queue are only accessed at user thread and mtcp thread respectively while user queue is shared among both threads. Adding events to the event queue is quite frequent whereas flushing events (requiring lock) takes place just once among hundreds or thousands of events. So we chose to queue the events in the mtcp queue, acquire lock, and push events in a batch.
