### ISSUE TITLE
Hi,I think we could add lua support?

### ISSUE THREAD

**Issue by xiyanxiyan10** [eunyoung14/mtcp#115]
Frame is used for project。
I have an idea.....
The core could run with c, Logic code run with lua if we have lua support upon core layers I think。

**Comment by ajamshed** [comment]
Xiyanxiyan10,

Can you please elaborate? Are you talking about a design in similar vein as [snabb](https://github.com/snabbco/snabb)?

**Comment by xiyanxiyan10** [comment]
Yeah, also  similar vein as skynet?

**Comment by ajamshed** [comment]
xiyanxiyan10,

This looks like an interesting idea. And I encourage you to come up with a general design plan. I have limited experience in lua. But I can contribute in this project if I have some helping hands. One question, how much performance degradation can we expect if the application context of mTCP is changed to lua language?

**Comment by xiyanxiyan10** [comment]
Just a little cost。
Lua support only on logic layer。
As a result, Users’code seperated from the mtcp core， We hold maintenance of mtcp core。
I think we could refer to the result of the “skynet” project。

**Comment by ajamshed** [comment]
Sounds good.
