### ISSUE TITLE
Multipath TCP Support?

### ISSUE THREAD

**Issue by aunali1** [eunyoung14/mtcp#116]
Draft RFC is [here](https://tools.ietf.org/html/draft-ietf-mptcp-rfc6824bis-07)

> TCP/IP communication is currently restricted to a single path per
   connection, yet multiple paths often exist between peers.  The
   simultaneous use of these multiple paths for a TCP/IP session would
   improve resource usage within the network and, thus, improve user
   experience through higher throughput and improved resilience to
   network failure.

**Comment by ajamshed** [comment]
Aun,

MP-TCP integration is in our plans but it may take some time before we start working on this module.
We are currently following this priority [list](https://github.com/eunyoung14/mtcp/wiki/Supported-Features) of TODOs.

**Comment by sskras** [comment]
Now the newer RFC is out: the [RFC 8684](https://datatracker.ietf.org/doc/html/rfc8684)

It introduces v1 (the in-tree version) of the MPTCP, whereas v0 was an out-of-tree implementation for Linux kernel.  The explanation:
https://www.mptcp.dev/faq.html#mptcpv0-vs-mptcpv1
