### ISSUE TITLE
Can I use mtcp for a proxy application?

### ISSUE THREAD

**Issue by JungukCho** [eunyoung14/mtcp#117]
Hi, All.

Thank you for a great project.
I am new to mTCP and have a simple question.
I can successfully run epserver and epwget which run as a server and client separately.
I just wonder whether I can build a proxy application with mTCP which functions as a server and multiple client at the same time. If so, is there any poniter example?

Thanks,
Junguk

**Comment by ajamshed** [comment]
Hi JungukCho,

Can you please elaborate a little more on your design? Building a proxy application using mTCP may work, but the mTCP core stack may (or may not) need to be tweaked (depending on your setup).

**Comment by JungukCho** [comment]
Hi, ajamshed.

Thank you for reply.

My design is basically one application can work server and clients at the same time in high level.
In detail, one thread in one application can listen to connections from clients in one thread like epserver example and the other thread in the application will work as clients to connect other hosts.
They are long-live TCP connections.

but the mTCP core stack may (or may not) need to be tweaked (depending on your setup).
-> Could you explain more please?

Thanks.

**Comment by ajamshed** [comment]
I think you should go ahead and start developing the application. Please contact me in case you face any issues.
