### ISSUE TITLE
Bug in timeout and retransmission of control pkt

### ISSUE THREAD

**Issue by GroBam** [eunyoung14/mtcp#12]
I checked in timer.c and there are some points:
- In CheckRtmTimeout, if stream timed-out, then it falls into this block of code

ret = HandleRTO(mtcp, cur_ts, walk);
TAILQ_REMOVE(rto_list, walk, sndvar->timer_link);
mtcp->rto_list_cnt--;
walk->on_rto_idx = -1;

- HandleRTO will call functions in tcp_out.c: AddtoControlList -> SendControlPacket -> SendTCPPacket

- In SendTCPPacket, at the end it will call AddtoRTOList

- Now in AddtoRTOList, there is a condition

if (cur_stream->on_rto_idx < 0 ) {

It will be false because it already in some rto_list, so that the line
mtcp->rto_list_cnt++;

will not be met.

- After finishing HandleRTO, rto_list_cnt decreased and stream is took out of rto_list

Seeing all the above lines of code, I think those will make the stream I need to continue checking for timeout and retransmission out of the timer list.
Besides, because rto_list_cnt decreases here and when ACKed, it might lead to situation when rto_list_cnt == 0 and then mtcp->rto_store->rto_now_idx will be reset to 0,
which will ignore all the stream at high offset when traverse the list

**Comment by eunyoung14** [comment]
This issue was solved.
