### ISSUE TITLE
epserver doesn't answer client when client reboots frequenly 

### ISSUE THREAD

**Issue by StarSkyTV** [eunyoung14/mtcp#120]
Hi 
 I use standard socket as a client to send packet to epserver. 
My test order are as follows:
1. start client
2. send packet to epserver
3. after a few minutes, stop client.
4. continue to do step 1,2,3
after a few tests，when I reboot client again, client can't read packets from epserver.
I catch the nic packet with tcpdump. I found the three handshake has completed, 
and client push data to epserver and receive ack frame from epserver, but epserver does not answer a data frame to client.
Only reboot epserver can solve this problem.

Please give me some advisement, thank you very much!

Best wishes!

**Comment by ajamshed** [comment]
Is your client directly attached to the server? Or is there a switch between the two machines?

In case the client is directly attached to the server, it is possible that the dpdk-enabled interface fails to bring the link up when the client gets rebooted. I will do some tests on my side. Can you check whether you
see similar issues when you are using ``example/`` programs from dpdk toolkit?
