### ISSUE TITLE
mTCP is not configured properly when running ab

### ISSUE THREAD

**Issue by lybmath** [eunyoung14/mtcp#124]
When running ab on our sever with 24 logical cores, we always get an error said that "**[ mtcp_init:1414] You cannot run mTCP with more than 16 cores due to NIC hardware queues restriction. Please disable the last 8 cores in your system**"

Besides, no matter how many cores are specified by the option '-N', the above error arises all the time.

Finally, we found the key reasons:
1/ what the option '-N' specifies will never take effect in mTCP's configuration (i.e. the value of CONFIG._num_cores_ is 0)
2/ _num_cpus_ will be set to the number of available logical cores (by **GetNumCPUs()**)
3/ when _num_cpus_ (that's 24 in our case)  is larger than MAX_CPUS (16), the above error arises.
4/ 2/ and 3/ are executed before **LoadConfiguration()** so that specifying the number of cores in the _config_file_ has no effect as well.

**Comment by ajamshed** [comment]
Thanks for reporting the issue. I understand that you have a fix for this issue as well. I am looking forward for the solution soon.

**Comment by ajamshed** [comment]
Thanks. I have merged your fix.
