### ISSUE TITLE
Failed to find appropriate sender if configuring mTCP with discrete ports

### ISSUE THREAD

**Issue by lybmath** [eunyoung14/mtcp#125]
When configuring mTCP-dpdk with two ports _dpdk0_ _dpdk2_, or with continues ports starting from a port whose index is not 0 (e.g. _dpdk1_), we will get the error "**[ GetSender: 795] (NEVER HAPPEN) Failed to find appropriate sender.**"

The problem may be:

there are actually two types of indexes to identify one configured interface (if virtualization on network interface is enabled there is another type, but it's not discussed here):

1/ the index of the list of configured interfaces in the _config_file_. They are used to locate any configured interface in CONFIG._eths_ and its corresponding packet buffers within the private context of each mTCP instance. For example, the configuration _dpdk0_ _dpdk2_ will be loaded as 0 and 1 in index of this type.

2/ the index of physic interfaces. They are used to configure, start and stop physic interfaces. For example, the indexes of  _dpdk0_ and _dpdk2_ of this type must be 0 and 2 respectively.

different types are useful in different places. A proper mapping is required and which to use in a given place should be clarified carefully.

**Comment by ajamshed** [comment]
Thanks for reporting the issue. I am looking forward to seeing your patch.
