### ISSUE TITLE
get unexpected error in mystrtol

### ISSUE THREAD

**Issue by lybmath** [eunyoung14/mtcp#128]
We got a strange error said "strtol: file or directory not exist" these days.

In our case:
1/ we indeed tried to open an non-existing file before calling _mystrtol_. But this will not terminate the whole process and has nothing to do with _strtol_. Due to this point, the errno becomes 2 before calling _mystrtol_.
2/ tcp_timeout is set to 0 in our config file. So, when calling _mystrtol_ during loading configurations, we get 0 from calling _strtol_.

Accordingly, we reset _errno_ to 0 before calling _strtol_ and this does address this issue in our case. But we are not sure whether it is a proper solution in general.

**Comment by ajamshed** [comment]
Hi,

I think you have detected a valid bug. According to [https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=6619179](https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=6619179), ``errno`` needs to be set to 0 before calling strtol. This needs to be fixed.

**Comment by ajamshed** [comment]
Thanks I have merged your fix.
