### ISSUE TITLE
Missing RTO update for timed-out stream not ESTABLISHED

### ISSUE THREAD

**Issue by GroBam** [eunyoung14/mtcp#13]
In timer.c, function HandleRTO, there is a condition

/\* update rto timestamp */
if (cur_stream->state >= TCP_ST_ESTABLISHED) {

So only stream which is ESTABLISHED or has state above will be updated its rto value.

Otherwise, stream like SYN_SENT will not and continues using old rto (1000ms) => not obey the RFC

**Comment by eunyoung14** [comment]
Hi, the states under established will be SYN_SENT or SYN_RCVD state.
In those states, there will be no ACK received from the peer, meaning that no RTT has been calculated.
Do you mean we need to do exponential backoff for this case?

**Comment by GroBam** [comment]
I remember that RTT only involves in calculating RTO of streams established.

For SYN_SENT, the new RTO will be the old one multiple by 2. Which equals to (initial timeout)* 2^n
n is number of retransmission times
Most of the times, initial timeout of TCP will be 1 second so that the RTO of stream will be 2^n

**Comment by GroBam** [comment]
You can view some streams in that circumstance in wireshark, their RTO grow exponential

**Comment by eunyoung14** [comment]
Ok. I'll make the following update for this.
