### ISSUE TITLE
dpdk0 does not appear 82599ES NIC

### ISSUE THREAD

**Issue by kingsonstar** [eunyoung14/mtcp#130]
Hi, mtcp team,

I can build DPDK and mTCP successfully,  but  after binding Ethernet device(82599ES ) to IGB UIO module dpdk0 does not appear.
The NIC: 82599ES 10-Gigabit SFI/SFP+ Network Connection

Have any opinion about this issue? Am I missing some step?  
Thanks in advance.

**Comment by kingsonstar** [comment]
Have checked lspci -x as:

**Comment by kingsonstar** [comment]
Have checked lspci -x as:
82:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
00: 86 80 fb 10 07 04 10 00 01 00 00 02 10 00 80 00
10: 04 00 e2 fb 00 00 00 00 21 f0 00 00 00 00 00 00
20: 04 40 e4 fb 00 00 00 00 00 00 00 00 ff ff ff ff
30: 00 00 00 00 40 00 00 00 00 00 00 00 0b 01 00 00

82:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
00: 86 80 fb 10 07 04 10 00 01 00 00 02 10 00 80 00
10: 04 00 e0 fb 00 00 00 00 01 f0 00 00 00 00 00 00
20: 04 00 e4 fb 00 00 00 00 00 00 00 00 ff ff ff ff
30: 00 00 00 00 40 00 00 00 00 00 00 00 0a 02 00 00

**Comment by kingsonstar** [comment]
and have checked ixgbe_type.h:
===============
#define IXGBE_DEV_ID_82599_CX4                  0x10F9
#define IXGBE_DEV_ID_82599_SFP                  0x10FB
#define IXGBE_SUBDEV_ID_82599_SFP               0x11A9
==================
Does that mean our mTCP can support 82599ES?

**Comment by 358405961** [comment]
Hi kingsonstar
    The issue #62 may be similar to yours, and I got the same problem in my test environment. My kernel is 3.10.0-327,  network device is Intel I350.
    I got the problem which is exactly the same as the issue #62 . So I am thinking is there any possibility that the patched igbuio_pci_probe function is not compatible with the kernel 3.10.0 ?
    You could check you kernel version and dmesg output info to see whether or not the netdev is registered ok.

**Comment by kingsonstar** [comment]
@358405961 my kernel version still is 3.10.0,  and from the output of dmesg, the netdev is registered ok
my testing kernel version is: 3.10.0-123.el7.x86_64

the dmesg:
[ 1420.071394] ixgbe 0000:82:00.0: removed PHC on ens3f0
[ 1420.170047] ixgbe 0000:82:00.0: complete
[ 1420.170363] igb_uio 0000:82:00.0: irq 143 for MSI/MSI-X
[ 1420.170569] igb_uio 0000:82:00.0: ifindex picked: 0
[ 1420.170691] igb_uio 0000:82:00.0: uio device registered with irq 8f

**Comment by kingsonstar** [comment]
One more  point:
after binding the NIC to igb_uio driver.  ifconfig can show the orig netdev name and can ping it.  dose that mean the netdev is registered successfully,  mTCP-DPDK just donot change the netdev name to dpdk0,

**Comment by ajamshed** [comment]
It looks most likely that your kernel is renaming the registered interface. I should probably update the README file to mention this point. Can you please check your ``dmesg`` log and see if you see a line similar to:

``[1529611.079881] igb_uio 0000:82:00.0 enp130s0f0: renamed from dpdk0``

Once you attach the Ethernet interface with ``igb_uio`` module, quit the ``dpdk-setup.sh`` script and run the following command:

`$ sudo ip link set enp130s0f0 name dpdk0`
(I am assuming that ``enp130s0f0`` is the newly named interface).

Once the interface name is re-set, please run the ``setup_iface_single_process.sh`` script.

**Comment by kingsonstar** [comment]
Have checked the dmesg log,  it dosenot include  any message about "0000:82:00.0 enp130s0f0: renamed from dpdk0 ".

**Comment by kingsonstar** [comment]
Hi ajamshed 

On my another testing machine whoes nic is 82545EM ,  dpdk0 does not appear when run ifconfig.
but the dmesg log as:
==============
[ 8182.182768] igb_uio: Use MSIX interrupt by default
[ 8206.010432] igb_uio 0000:02:01.0: PCI INTX mask not supported
[ 8206.010711] igb_uio 0000:02:01.0: ifindex picked: 0
[ 8206.021194] igb_uio 0000:02:01.0: uio device registered with irq 0
[ 8206.130634] systemd-udevd[4444]: renamed network interface dpdk0 to eno16777736
=====================

Binding Ethernet device(eno16777736) to IGB_UIO module, as:
=================
Network devices using DPDK-compatible driver
============================================
0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper)' drv=igb_uio unused=

Network devices using kernel driver
===================================
<none>

Other network devices
=====================
<none>
==================

My issue is:   after binding to IGB_UIO module,  I cannot ping ethernet device(eno16777736) any more.
Have any opinion about this issue?

**Comment by kingsonstar** [comment]
Hi ajamshed

On my another testing machine whoes nic is 82545EM , dpdk0 does not appear when run ifconfig.
but the dmesg log as:

[ 8182.182768] igb_uio: Use MSIX interrupt by default
[ 8206.010432] igb_uio 0000:02:01.0: PCI INTX mask not supported
[ 8206.010711] igb_uio 0000:02:01.0: ifindex picked: 0
[ 8206.021194] igb_uio 0000:02:01.0: uio device registered with irq 0
[ 8206.130634] systemd-udevd[4444]: renamed network interface dpdk0 to eno16777736

Binding Ethernet device(eno16777736) to IGB_UIO module, as:

Network devices using DPDK-compatible driver

0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper)' drv=igb_uio unused=

Network devices using kernel driver

Other network devices

==================
My issue is: after binding to IGB_UIO module, I cannot ping ethernet device(eno16777736) any more.
Have any opinion about this issue?

**Comment by ajamshed** [comment]
For your last example, you should run the following command:
`# sudo ip link set eno16777736 name dpdk0`

Please note that you will not receive a ping response from the machine (unless you have an mTCP application running). ``igb_uio`` module detaches the NIC port from the linux kernel completely.

**Comment by 358405961** [comment]
Hi ajamshed

I got the same problem, the dmesg info is  as below

[ 1764.985714] igb_uio: Use MSIX interrupt by default
[ 1770.489768] igb 0000:02:00.1: removed PHC on eth1
[ 1770.494506] igb 0000:02:00.1: DCA disabled
[ 1770.509517] igbuio_pci_probe: start
[ 1770.513117] igb_uio 0000:02:00.1: irq 43 for MSI/MSI-X
[ 1770.513137] igb_uio 0000:02:00.1 (unregistered net_device): 
[ 1770.513140] igbuio_pci_probe: 2 dpdk%d
[ 1770.516992] igbuio_pci_probe: 3 dpdk0
[ 1770.520682] igbuio_pci_probe: 0
[ 1770.523844] igb_uio 0000:02:00.1: ifindex picked: 0
[ 1770.528809] igb_uio 0000:02:00.1: uio device registered with irq 2b
[ 1770.535110] igbuio_pci_probe: success
[ 1795.757538] igb 0000:02:00.1: irq 43 for MSI/MSI-X

the messages with "igbuio_pci_probe" is what I added. Seems like there is no renaming messages

**Comment by ajamshed** [comment]
Can you show me the output of ``ifconfig -a``?
What happens when you run ``setup_iface_single_process.sh`` script?

**Comment by 358405961** [comment]
Hi ajamshed

the origin ifconfig -a shows like below:

bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 0  (Ethernet)
        RX packets 1000177  bytes 495881600 (472.9 MiB)
        RX errors 0  dropped 168  overruns 0  frame 0
        TX packets 57358  bytes 4980149 (4.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether 0c:c4:7a:73:1a:b6  txqueuelen 1000  (Ethernet)
        RX packets 103116  bytes 139395305 (132.9 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 44074  bytes 3643746 (3.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdf920000-df93ffff  

eth1: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether 0c:c4:7a:73:1a:b6  txqueuelen 1000  (Ethernet)
        RX packets 897063  bytes 356486479 (339.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13297  bytes 1338845 (1.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdf900000-df91ffff  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 2253  bytes 224756 (219.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2253  bytes 224756 (219.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I should disable bond config to run dpdk, I just remove and change the ifcfg-bond0 and ifcfg-eth0 file, after that the ifconfig -a shows like below:

$ ifconfig -a
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 0  (Ethernet)
        RX packets 1007511  bytes 496332476 (473.3 MiB)
        RX errors 0  dropped 169  overruns 0  frame 0
        TX packets 57975  bytes 5063037 (4.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 1000  (Ethernet)
        RX packets 103518  bytes 139425254 (132.9 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 44319  bytes 3673991 (3.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdf920000-df93ffff  

eth1: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 0c:c4:7a:73:1a:b7  txqueuelen 1000  (Ethernet)
        RX packets 903997  bytes 356907590 (340.3 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 13667  bytes 1390770 (1.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdf900000-df91ffff  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 2253  bytes 224756 (219.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2253  bytes 224756 (219.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

After binding igb_uio to eth1, the ifconfig -a shows like below:

$ ifconfig -a
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 0  (Ethernet)
        RX packets 1015229  bytes 496818040 (473.8 MiB)
        RX errors 0  dropped 178  overruns 0  frame 0
        TX packets 59687  bytes 5309328 (5.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 1000  (Ethernet)
        RX packets 111236  bytes 139910818 (133.4 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 46031  bytes 3920234 (3.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdf920000-df93ffff  

eth1: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 0c:c4:7a:73:1a:b7  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 2253  bytes 224756 (219.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2253  bytes 224756 (219.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

when I run setup_iface_single_process.sh script, I got

$ sudo dpdk-16.11/tools/setup_iface_single_process.sh 1
igb_uio is loaded!
/home/qixi.hhy/git/mtcp
/sbin/ifconfig dpdk0 192.168.0.1 netmask 255.255.255.0 up
SIOCSIFADDR: No such device
dpdk0: ERROR while getting interface flags: No such device
SIOCSIFNETMASK: No such device
dpdk0: ERROR while getting interface flags: No such device

and after i change the script from dpdk0 to eth1, I got

$ sudo dpdk-16.11/tools/setup_iface_single_process.sh 1
igb_uio is loaded!
/home/qixi.hhy/git/mtcp
/sbin/ifconfig eth1 192.168.0.1 netmask 255.255.255.0 up

then the ifconfig -a shows like below

$ ifconfig -a
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 0  (Ethernet)
        RX packets 1022386  bytes 497276229 (474.2 MiB)
        RX errors 0  dropped 180  overruns 0  frame 0
        TX packets 60668  bytes 5450488 (5.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 1000  (Ethernet)
        RX packets 118393  bytes 140369007 (133.8 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 47012  bytes 4061442 (3.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdf920000-df93ffff  

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.1  netmask 255.255.255.0  broadcast 192.168.0.255
        ether 0c:c4:7a:73:1a:b7  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 2253  bytes 224756 (219.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2253  bytes 224756 (219.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by ajamshed** [comment]
358405961,

This is what you need to do:

1- Follow step 1 from README.md file.

2- Before doing step 2 (running ./setup_iface_single_process.sh script), type the following command:
`$ sudo ip link set eth1 name dpdk0`

3- Then run steps 2, 3, 4, 5, & 6 from README.md file.

Let me know if you still face issues.

**Comment by 358405961** [comment]
Hi ajamshed

After I setting eth1 name, the ifconfig -a  command shows the following result:

```
$ sudo ip link set eth1 name dpdk0

$ ifconfig -a
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 0  (Ethernet)
        RX packets 3830862  bytes 699484883 (667.0 MiB)
        RX errors 0  dropped 2791  overruns 0  frame 0
        TX packets 390613  bytes 99705990 (95.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

dpdk0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 0c:c4:7a:73:1a:b7  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        inet 10.213.250.174  netmask 255.255.252.0  broadcast 10.213.251.255
        ether 0c:c4:7a:73:1a:b6  txqueuelen 1000  (Ethernet)
        RX packets 2926869  bytes 342577661 (326.7 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 376960  bytes 98317430 (93.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xdf920000-df93ffff  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 2621  bytes 282718 (276.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2621  bytes 282718 (276.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

And every step after that runs ok. Does this still means that the OS change the interface name quietly or there is something other problem？thanks.

**Comment by ajamshed** [comment]
It looks like the OS changed the interface name. Please check `/var/log/messages` file and/or see if any NetworkManager is running in your system.

**Comment by royceniu** [comment]
Hi, I also met this issue and fixed this by @ajamshed 's solution.
