### ISSUE TITLE
mtcp_setsockopt do not work

### ISSUE THREAD

**Issue by WenqingWu** [eunyoung14/mtcp#135]
Hi，
In mtcp，the function mtcp_setsockopt haven't been implemented thoroughly?
And the socket created by mtcp_socket is invalid for Linux api setsockopt( )，anyone has any suggestions?

**Comment by ajamshed** [comment]
Hi Wenqing Wu,

You are right. ``mtcp_setsockopt()`` currently does not support socket option. Which socket option do you want to use? Linux API's ``setsockopt()`` would not work.

**Comment by 358405961** [comment]
Hi

1. the mtcp_setsockopt implements nothing, so of course it's not work
2. the mtcp socket is not generated by kernel, it is mantained by local thread. If you want to set any option like in kernel, you'd better implement by yourself

**Comment by WenqingWu** [comment]
Hi ,thanks for your reply.
The socket option I want to use id SO_REUSEADDR

**Comment by ajamshed** [comment]
Hi Wenqing,

I'm afraid you'll have to implement this socket option on your own.
