### ISSUE TITLE
will mTCP support TSO/GSO?

### ISSUE THREAD

**Issue by simpx** [eunyoung14/mtcp#139]
will mTCP support TSO/GSO?

helpful link: http://dpdk.org/ml/archives/dev/2014-May/002537.html

**Comment by ajamshed** [comment]
Hi simpx,

We do have plans to incorporate TSO in mTCP. The only down-point of implementing this feature is that I will have to end up making a separate branch for the netmap version of mTCP (I don't want to include dpdk-specific functions in the netmap version). I may end up implementing this feature this year (or much sooner if I get free time :))

**Comment by simpx** [comment]
@ajamshed thx!

I run mTCP with dpdk, I'll try to implements a specific version first :)

**Comment by bhakta0007** [comment]
I am evaluating using mTCP for a project and wanted to check if TSO is supported. Was this done?

**Comment by ajamshed** [comment]
@bhatka0007,

TSO is not yet supported.
