### ISSUE TITLE
where is HUGETABLE defined?

### ISSUE THREAD

**Issue by simpx** [eunyoung14/mtcp#141]
as I know `HUGEPAGE` is defined in [mtcp/src/Makefile.in](https://github.com/eunyoung14/mtcp/blob/14c4652e18f3aa2c84a53197c4fb4fc706deed79/mtcp/src/Makefile.in#L71) when `libhugetlbfs.so` is found.

but where is `HUGETABLE` defined?

1. It seems like `hugepage` will not enabled without it in [memory_mgt.c#L8](
https://github.com/eunyoung14/mtcp/blob/14c4652e18f3aa2c84a53197c4fb4fc706deed79/mtcp/src/memory_mgt.c#L8)

2. I can't find any `Makefile.in` includes `-lhugetlbfs`

What is the proper way to use mTCP with Hugepage?

**Comment by ajamshed** [comment]
The code related to hugepages is currently outdated. When we were initially testing mTCP with hugepages we did not really get substantial performance improvement. We gradually stopped maintaining the code. That part of the code either needs to be cleaned up or needs to be updated.
