### ISSUE TITLE
apache web server over mtcp

### ISSUE THREAD

**Issue by kheirabadi** [eunyoung14/mtcp#143]
Hi, thank you for your great work.
I'm trying to change apache web server to use mtcp. I used your APR (in apps/apache_benchmark) with small modifications for socket listen & accept API using mtcp. also called mtcp_init and mtcp_create_context in apache code.
I use a single process, a listener thread and 2 worker threads in it. If num_cores == 1 then all things are OK and server correctly works. but if num_cores == 2 then half of requests are served. 
additional data:
listener_thread on core 0
worker_threads on core 0, 1

I think each call to mtcp_create_context initialize a separate mtcp stack affinitize to a particular core and therefore a separate listener_thread also needed. is this correct?

**Comment by ajamshed** [comment]
Hi kheirabadi,

You are partially correct (``mtcp_create_context()`` creates a separate mTCP stack instance). But if you are using an mTCP-based solution, you would not need a separate (dedicated) listener thread. Each worker thread will also handle the connection request listening task. mTCP stack follows a run-to-completion model. I suggest that you go through ``epserver.c`` code and also our [paper](https://www.usenix.org/system/files/conference/nsdi14/nsdi14-paper-jeong.pdf) to get a clearer idea.
