### ISSUE TITLE
mtcp_epoll_wait

### ISSUE THREAD

**Issue by kheirabadi** [eunyoung14/mtcp#146]
Hi,
I'm trying to use mtcp in my application. I have two threads: a listener which wait for new connection and accepting it and the other worker thread who work on the newly accepted socked. listener always call mtcp_epoll_wait (with unlimited timeout == -1) and in some situation worker thread also need mtcp_epoll_wait (to know when data arrive and sent) but whenever worker thread call mtcp_epoll_wait, something in listener thread goes wrong and never returns from its mtcp_epoll_wait.
how can I remove this limitation?
Regards

**Comment by ajamshed** [comment]
Hi kheirabadi,

There is currently a restriction in the mTCP stack that allows users to create only a single ``epoll`` instance per mTCP context. Is there a way you can combine both listener and worker tasks to a single ``epoll`` instance? In case that is not possible, then I suggest that you modify ``mtcp.h`` and ``evenpoll.c`` files from ``mtcp/src/``. Currently the ``mtcp_manager`` struct contains only a single ``epoll`` instance.

**Comment by kheirabadi** [comment]
Is bellow changes are enough to have at most 100 epoll calls in the application per context?
with the restriction a socket only belong to one epoll instance?
mtcp.h:
    struct mtcp_manager
    {
          ....
         struct mtcp_epoll *ep[100];
         ....
     }

eventpoll.c:
     int mtcp_epoll_create(mctx_t mctx, int size, int which)
     {
            ...
           mtcp->ep[which] = ep;
           epsocket->ep = ep;
           ....
      }

      int CloseEpollSocket(mctx_t mctx, int epid, which)
      {
            ...
            mtcp->ep[which] = NULL;
	    mtcp->smap[epid].ep = NULL;
            ...
      }

**Comment by ajamshed** [comment]
kheirabadi,

You'll have to do more changes to get this working. ``mtcp->ep`` handle is used to transport events from mTCP thread context to app thread context (and vice versa). So you'll have to incorporate some changes to all functions that are using ``mtcp->ep``. I suggest that you do a grep on ``mtcp->ep`` inside ``mtcp/src`` to scan where in the code ``mtcp->ep`` is being accessed.
