### ISSUE TITLE
bug in mtcp_accept

### ISSUE THREAD

**Issue by netinov** [eunyoung14/mtcp#148]
Hi all,
I wanna use MTCP in my web server very similar to apache. it works but after serving successful 1,000,000 transactions (ab -n 1000000 -c 100 ...), something in MTCP goes wrong. I found extra items remains in acceptq and when StreamDequeue continue to dequeu them one by one, some of tcp_stream items has socket field with value of 0x1. this condition lead to segmentation fault. I don't have any idea why this situation occurred, can you give me help?
Regards

**Comment by ajamshed** [comment]
Hi,

This is a kind of bug which will be difficult to debug without knowing more details. You need to first make sure whether the memory corruption (overwrite etc.) is taking place due to the application code or the mTCP stack itself. To ensure this, please make sure that your web server code works fine when you use normal BSD sockets first.

**Comment by netinov** [comment]
my webserver is fine with standard BSD sockets. I suspect mtcp stack accept a single connection twice, is it possible?

**Comment by netinov** [comment]
this problem exists with concurrent connections, and if there is only one connection (ab -n 1000000 -c 1 ..) this situation does not occurred.

**Comment by netinov** [comment]
I add a counter in ProcessTCPPacket and counts number of CreateNewFlowHTEntry and also add another counter in mtcp_accept and counts number of accepted streams. these two counters reports more than streams than ab generated. 
ab reports 1000000 transactions, but these two counters reports about 1000050 and the problem exists in processing these extra 50 streams.

**Comment by netinov** [comment]
I found these extra streams has state == 7 (TCP_ST_CLOSE_WAIT) rather than 4 (TCP_ST_ESTABILSHED). what happened for these streams?

**Comment by netinov** [comment]
these situations also exists for (ab -n 1000  -c 100). these broken streams remain in acceptq and newly streams inserted at the end of it. so new streams never handled by application. I don't know how to fix it.

**Comment by netinov** [comment]
****I see the errorneous stream get closed by the client before it is accepted by server application.**
**I see the errorneous stream get closed by the client before it is accepted by server application.****

**Comment by netinov** [comment]
I add a code snippet in Handle_TCP_ST_ESTABLISHED, when receiving FIN, to search acceptq and delete corresponding stream. it works but I don't know it is a good solution

**Comment by ajamshed** [comment]
This does not look like an ideal solution. I will try to run some tests and see if I can recreate this bug in my system.

**Comment by donlvsml** [comment]
I also get the segmentation fault when some of tcp_stream items has socket field with value of 0x1 in my case.  I find it is caused in destroyq queue, and the corresponding stream was destroyed, i.e.  tcp stack from tcp_in.c calls DestroyTCPStream() to destroy it, but the stream is still in destroyed queue. The DestroyTCPStream function is not re-enter safely, it seems the connectq/acceptq/closeq/resetq have the same problem.

I change the destroyed queue to a bidirectional list, and delete the stream from the list in DestroyTCPStream, now the segmentation fault has not recurrent. You can check these codes, many thx.

**Comment by ajamshed** [comment]
@donlvsml, @netinov,

Thanks for reporting the bug. Can you both please share (or point to) the diff of the code that you made to fix the reported issue?
