### ISSUE TITLE
Build failure: aclocal-1.14: command not found

### ISSUE THREAD

**Issue by yilongli** [eunyoung14/mtcp#149]
I do have a newer version of aclocal installed:
```
yilongl@rcmaster:/shome/mtcp$ aclocal --version
aclocal (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

Changing ```am__api_version='1.14'``` to ```am__api_version='1.15'``` at https://github.com/eunyoung14/mtcp/blob/master/configure#L4186 seems to fix the problem for me.

**Comment by ajamshed** [comment]
Alternative: did you try running this command instead?:

``autoreconf -ivf``

This may also resolve the issue mentioned. Please let me know if this did not work. I will then try updating the autoconf files.
