### ISSUE TITLE
apache bench Makefile dpdk lib support

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#15]
Hi, 

I am testing mtcp with dpdk on ubuntu 14.04 with 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I believe the apache bench configure/Makefile file only support packet i/o ps, not updated to support dpdk packet io library build as seen from error below:

/bin/bash /usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/libtool --silent --mode=link  gcc -g -O2 -pthread   -DHAVE_CONFIG_H -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I./include -I/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/include/arch/unix -I./include/arch/unix -I/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/include/arch/unix -I/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/include -I/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/../../../../mtcp/include -I/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/../../../../io_engine -version-info 4:6:4 -L/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/../../../../mtcp/lib -L/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr/../../../../io_engine/lib   -o libapr-1.la -rpath /usr/local/apache2/lib passwd/apr_getpass.lo strings/apr_cpystrn.lo strings/apr_fnmatch.lo strings/apr_snprintf.lo strings/apr_strings.lo strings/apr_strnatcmp.lo strings/apr_strtok.lo tables/apr_hash.lo tables/apr_tables.lo atomic/unix/builtins.lo atomic/unix/ia32.lo atomic/unix/mutex.lo atomic/unix/ppc.lo atomic/unix/s390.lo atomic/unix/solaris.lo dso/unix/dso.lo file_io/unix/buffer.lo file_io/unix/copy.lo file_io/unix/dir.lo file_io/unix/fileacc.lo file_io/unix/filedup.lo file_io/unix/filepath.lo file_io/unix/filepath_util.lo file_io/unix/filestat.lo file_io/unix/flock.lo file_io/unix/fullrw.lo file_io/unix/mktemp.lo file_io/unix/open.lo file_io/unix/pipe.lo file_io/unix/readwrite.lo file_io/unix/seek.lo file_io/unix/tempdir.lo locks/unix/global_mutex.lo locks/unix/proc_mutex.lo locks/unix/thread_cond.lo locks/unix/thread_mutex.lo locks/unix/thread_rwlock.lo memory/unix/apr_pools.lo misc/unix/charset.lo misc/unix/env.lo misc/unix/errorcodes.lo misc/unix/getopt.lo misc/unix/otherchild.lo misc/unix/rand.lo misc/unix/start.lo misc/unix/version.lo mmap/unix/common.lo mmap/unix/mmap.lo network_io/unix/inet_ntop.lo network_io/unix/inet_pton.lo network_io/unix/multicast.lo network_io/unix/sendrecv.lo network_io/unix/sockaddr.lo network_io/unix/socket_util.lo network_io/unix/sockets.lo network_io/unix/sockopt.lo poll/unix/epoll.lo poll/unix/kqueue.lo poll/unix/poll.lo poll/unix/pollcb.lo poll/unix/pollset.lo poll/unix/port.lo poll/unix/select.lo random/unix/apr_random.lo random/unix/sha2.lo random/unix/sha2_glue.lo shmem/unix/shm.lo support/unix/waitio.lo threadproc/unix/proc.lo threadproc/unix/procsup.lo threadproc/unix/signals.lo threadproc/unix/thread.lo threadproc/unix/threadpriv.lo time/unix/time.lo time/unix/timestr.lo user/unix/groupinfo.lo user/unix/userinfo.lo   -lrt -lcrypt  -lpthread -ldl -lps -lmtcp -lnuma
/usr/bin/ld: cannot find -lps
collect2: error: ld returned 1 exit status
make[3]: *** [libapr-1.la] Error 1
make[3]: Leaving directory `/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib/apr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/mtcp/apps/apache_benchmark_deprecated/srclib'
make: *** [all-recursive] Error 1

I would like to add dpdk build for apache bench, which file in apache bench I should modify to add dpdk build support?

there are files  under apps/apache_benchmark_deprecated:

configure.in
Makefile.in
configure

I thought I should change configure.in, if so should I run buildconf to re-create the configure script?
I looked mtcp/configure and mtcp/configure.ac for reference, still not sure what detail configuration I should add dpdk for apache bench, any pointer would be helpful

**Comment by vincentmli** [comment]
I managed to compile ab with DPDK share lib  ok and ab runs ok with dpdk, here is the diff (hachish):
http://www.vcn.bc.ca/~vli/ab.diff.txt
my nic is Intel 82571EB, so modified mtcp to  load the DPDK pmd driver for Intel 82571EB with -d parameter to work with shared DPDK lib

**Comment by eunyoung14** [comment]
Hi Vincent,

I'm glad to hear that it's working fine now.
We were out of manpower to manage the ab by ourselves.
Thank you very much for your work and sharing it with us.
I'll test this patch on my  machines and make the changes to our repository.

**Comment by vincentmli** [comment]
I hard coded the PMD driver for my nic in io_module.c, so if you want to make the changes to your repository, you will have to make proper better patch for io_module.c for using the '-d' parameter to load PMD driver

**Comment by ajamshed** [comment]
Hi Vincent,
Thanks for the patch. Sorry for the delayed response. Like Eunyoung mentioned, we have been a bit busy with our normal day jobs and it sometimes get difficult to respond to mTCP-related issues quickly. We have updated ab. We still need to do extensive testing on mTCP applications with 1 Gbps ports. Therefore, the part of the patch related to libintel_dpdk has not been integrated yet. We will hopefully get to that in due time.
