### ISSUE TITLE
Missing dependency in the make file?

### ISSUE THREAD

**Issue by yilongli** [eunyoung14/mtcp#151]
For example, if I add a print statement ```fprintf(stderr, "dev_name_list: %s\n", dev_name_list);``` at https://github.com/eunyoung14/mtcp/blob/6babf3c75aa73a0c90c005d07e7de27ab6c135ab/mtcp/src/io_module.c#L225 and run ```make```, I won't see the change as I start ```epserver```. I have to remember to run ```make clean``` every time.

**Comment by ajamshed** [comment]
Thanks Yilongli,

The makefiles in ``mtcp/src/`` and ``apps/example/`` need major revisions. I plan to do them in the near future.

**Comment by ajamshed** [comment]
Done.
