### ISSUE TITLE
uint32 cur_ts overflow

### ISSUE THREAD

**Issue by simpx** [eunyoung14/mtcp#153]
in the code
```c
#define HZ                      1000
#define TIME_TICK               (1000000/HZ)        // in us
#define TIMEVAL_TO_TS(t)		(uint32_t)((t)->tv_sec * HZ + \
								((t)->tv_usec / TIME_TICK))
gettimeofday(&cur_ts, NULL);
uint32_t ts = TIMEVAL_TO_TS(&cur_ts);
```
t->tv_sec is about `1504256715`, so `tv_sec * HZ` is much bigger than 4294967295, the value of cur_ts is overflow.

**Comment by ajamshed** [comment]
simpx,

You are right that there is an overflow taking place. But we are only using ``TIMEVAL_TO_TS()`` value when computing time difference between two timestamps (both produced from ``TIMEVAL_TO_TS()``). So, logically, I am not seeing any major logical problems arising from this operation. 

However, we will think of a better way to code this logic.
