### ISSUE TITLE
mTCP OPTION Timestamp cause PAWS

### ISSUE THREAD

**Issue by simpx** [eunyoung14/mtcp#154]
see #153 , `cur_ts`  is unix time in ms

mTCP fill `cur_ts` in TCP option timestamp, but in linux kernel, the timestamp is filled with `jiffies`
 
When you run mTCP over VF (or some tech like this), your mTCP application will share the same IP with linux.

If your mTCP app and kernel communicate with the same server, and the server happens to enable the 'tw_recycle' option, the server will drop all kernel pkts because jiffies is always less than cur_ts

I think mTCP should try to use `jiffies` if possible

**Comment by ajamshed** [comment]
simpx,

That may work. Is there a way to retrieve jiffies value from userspace?
