### ISSUE TITLE
error: unknown field "ndo_set_vf_vlan" in the initializer

### ISSUE THREAD

**Issue by Sheridan** [eunyoung14/mtcp#158]
I am try to install mtcp to virtualboxed centos7 with 3.10.0-693.2.2.el7.x86_64 kernel.

```
cd dpdk-16.11
tools/dpdk-setup.sh

```
[13] x86_64-native-linuxapp-gcc

And got another error

```
In file included from /root/mtcp/git/mtcp/dpdk-16.11/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igbuio.c:35:0:
/root/mtcp/git/mtcp/dpdk-16.11/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:353:9: error: unknown field "ndo_set_vf_vlan" in the initializer
         .ndo_set_vf_vlan        = NULL,
         ^
```
Please, how can I fix this?

**Comment by ajamshed** [comment]
Hi Sheridan,

We provide mTCP support for linux kernel versions >= 3.13. Is there any way you can upgrade your system to a higher kernel? Thanks.
