### ISSUE TITLE
Using getsockopt to query connection status

### ISSUE THREAD

**Issue by jmmcgee** [eunyoung14/mtcp#16]
I am attempting to create a port the OpenMPI TCP btl module to use mtcp instead.  I have had and solved various other issues with this port.  But this problem seems to be a deficiency in mtcp's implementation of the sockets api:

Having attempted to connect to another machine, ompi attempts to use getsockopt to query the socket for its connection status asynchronously:

```
    if(mtcp_getsockopt(btl_endpoint->mctx, btl_endpoint->endpoint_sd, SOL_SOCKET, SO_ERROR, (char *)&so_error, &so_length) < 0) {
        BTL_ERROR(("mtcp_getsockopt() to %s failed: %s (%d)",
                   opal_net_get_hostname((struct sockaddr*) &endpoint_addr),
                   strerror(opal_socket_errno), opal_socket_errno));
        mca_btl_tcp_endpoint_close(btl_endpoint);
        return;
    }
    if(so_error == EINPROGRESS || so_error == EWOULDBLOCK) {
        return;
    }
    if(so_error != 0) {
        BTL_ERROR(("mtcp_connect() to %s failed: %s (%d)",
                   opal_net_get_hostname((struct sockaddr*) &endpoint_addr),
                   strerror(so_error), so_error));
        mca_btl_tcp_endpoint_close(btl_endpoint);
        return;
    }
```

![screenshot from 2015-08-03 14 51 58](https://cloud.githubusercontent.com/assets/920218/9048639/74e0112a-39ef-11e5-8280-2e56989a4d1f.png)
![screenshot from 2015-08-03 14 53 30](https://cloud.githubusercontent.com/assets/920218/9048640/761b40e6-39ef-11e5-8648-dfac2796d46a.png)

It fails however with `so_error=38`,  `strerror()` giving the explanation, 'Function not implemented'.

Believing this may have been a simple fix, I attempted to fix it myself (as I had verified with wireshark under certain conditions that the connection _was_ being established):

```
inline int 
GetSocketError(socket_map_t socket, void *optval, socklen_t *optlen)
{
    tcp_stream *cur_stream;

    if (!socket->stream) {
        errno = EBADF;
        return -1;
    }

    cur_stream = socket->stream;
    if (cur_stream->state == TCP_ST_CLOSED) {
        if (cur_stream->close_reason == TCP_TIMEDOUT || 
                cur_stream->close_reason == TCP_CONN_FAIL || 
                cur_stream->close_reason == TCP_CONN_LOST) {
            *(int *)optval = ETIMEDOUT;
            *optlen = sizeof(int);

            return 0;
        }
    }

    if (cur_stream->state == TCP_ST_CLOSE_WAIT || 
            cur_stream->state == TCP_ST_CLOSED) { 
        if (cur_stream->close_reason == TCP_RESET) {
            *(int *)optval = ECONNRESET;
            *optlen = sizeof(int);

            return 0;
        }
    }

//  if(cur_stream->state == TCP_ST_SYN_SENT) {
//      *(int *)optval = EINPROGRESS;
//      *optlen = sizeof(int);
//
//      return 0;
//  }
//  if(cur_stream->state == TCP_ST_ESTABLISHED)
//      return 0;
//
    errno = ENOSYS;
    return -1;
}
```

As the code did not work, I uncommented it.

I am not sure whether this is a trivial fix or not but any help would be appreciated.

EDIT: commented it out.

**Comment by eunyoung14** [comment]
Hi,
Sorry for late response.
I think your commented part would work if it's modified as follows.
Or you could check the return of the mtcp_getsockopt(), whether it returns 0.

```
if (cur_stream->state == TCP_ST_SYN_SENT) {
    *(int *)optval = EINPROGRESS;
    *optlen = sizeof(int);

    return 0;
}

if (cur_stream->state == TCP_ST_ESTABLISHED) {
    *(int *)optval = 0;
    *optlen = sizeof(int);
      return 0;
}
```
