### ISSUE TITLE
type of ht_count in struct hashtable is uint8_t, maybe should be uint16_t ?

### ISSUE THREAD

**Issue by tinnfu** [eunyoung14/mtcp#160]
in mtcp/src/include/fhash.h:23, typeof ht_count is uint8_t
 
 21 /* hashtable structure */
 22 struct hashtable {
 23     **uint8_t ht_count** ;                    // count for # entry
 24     uint32_t bins;
 25
 26     union {
 27         hash_bucket_head *ht_table;
 28         list_bucket_head *lt_table;
 29     };
 30
 31     // functions
 32     unsigned int (*hashfn) (const void *);
 33     int (*eqfn) (const void *, const void *);
 34 };

but in mtcp/src/fhash.c:82, use ht->ht_count as uint16_t

 74 int
 75 StreamHTInsert(struct hashtable *ht, void *it)
 76 {
 77     /* create an entry*/
 78     int idx;
 79     tcp_stream *item = (tcp_stream *)it;
 80
 81     assert(ht);
 82     **assert(ht->ht_count <= 65535); // uint16_t ht_count**
 83
 84     idx = ht->hashfn(item);
 85     assert(idx >= 0 && idx < NUM_BINS_FLOWS);
 86
 87     TAILQ_INSERT_TAIL(&ht->ht_table[idx], item, rcvvar->he_link);
 88
 89     item->ht_idx = TCP_AR_CNT;
 90     ht->ht_count++;
 91
 92     return 0;
 93 }

**Comment by ajamshed** [comment]
Hi tinnfu,

Thanks for reporting the issue. In fact, ``ht->count`` is not really required in the stack. I will remove that in my next commit.
