### ISSUE TITLE
mTCP with mellanox driver

### ISSUE THREAD

**Issue by hzeba** [eunyoung14/mtcp#163]
Hi,

I'm having some troubles running example apps with mellanox driver. I've compiled provided dpdk with CONFIG_RTE_LIBRTE_MLX5_PMD=y and testpmd works just fine:

```
# ./testpmd -c 0xff00 -n 4 -w 0000:19:00.1 -- --rxq=2 --txq=2
EAL: Detected 64 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:19:00.1 on NUMA socket 0
EAL:   probe driver: 15b3:1015 net_mlx5
PMD: net_mlx5: PCI information matches, using device "mlx5_1" (SR-IOV: false, MPS: true)
PMD: net_mlx5: 1 port(s) detected
PMD: net_mlx5: MPS is enabled
PMD: net_mlx5: port 1 MAC address is ec:0d:9a:3a:3b:5b
USER1: create a new mbuf pool <mbuf_pool_socket_0>: n=203456, size=2176, socket=0
USER1: create a new mbuf pool <mbuf_pool_socket_1>: n=203456, size=2176, socket=1
Configuring Port 0 (socket 0)
PMD: net_mlx5: 0xd171c0: TX queues number update: 0 -> 2
PMD: net_mlx5: 0xd171c0: RX queues number update: 0 -> 2
Port 0: EC:0D:9A:3A:3B:5B
Checking link statuses...
Done
No commandline core given, start packet forwarding
io packet forwarding - ports=1 - cores=1 - streams=2 - NUMA support enabled, MP over anonymous pages disabled
Logical Core 9 (socket 1) forwards packets on 2 streams:
  RX P=0/Q=0 (socket 0) -> TX P=0/Q=0 (socket 0) peer=02:00:00:00:00:00
  RX P=0/Q=1 (socket 0) -> TX P=0/Q=1 (socket 0) peer=02:00:00:00:00:00

  io packet forwarding - CRC stripping enabled - packets/burst=32
  nb forwarding cores=1 - nb forwarding ports=1
  RX queues=2 - RX desc=128 - RX free threshold=0
  RX threshold registers: pthresh=0 hthresh=0 wthresh=0
  TX queues=2 - TX desc=512 - TX free threshold=0
  TX threshold registers: pthresh=0 hthresh=0 wthresh=0
  TX RS bit threshold=0 - TXQ flags=0x0
```

It binds to the interface and the server stops responding on it. The epserver app on the other hand initializes without any errors but doesn't bind to any of the interfaces:

```
# ./epserver -p /var/www -f epserver.conf -N 1
Configuration updated by mtcp_setconf().
---------------------------------------------------------------------------------
Loading mtcp configuration from : epserver.conf
Loading interface setting
EAL: Detected 64 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:19:00.0 on NUMA socket 0
EAL:   probe driver: 15b3:1015 net_mlx5
PMD: net_mlx5: PCI information matches, using device "mlx5_0" (SR-IOV: false, MPS: true)
PMD: net_mlx5: 1 port(s) detected
PMD: net_mlx5: MPS is enabled
PMD: net_mlx5: port 1 MAC address is ec:0d:9a:3a:3b:5a
EAL: PCI device 0000:19:00.1 on NUMA socket 0
EAL:   probe driver: 15b3:1015 net_mlx5
PMD: net_mlx5: PCI information matches, using device "mlx5_1" (SR-IOV: false, MPS: true)
PMD: net_mlx5: 1 port(s) detected
PMD: net_mlx5: MPS is enabled
PMD: net_mlx5: port 1 MAC address is ec:0d:9a:3a:3b:5b
Configurations:
Number of CPU cores available: 1
Number of CPU cores to use: 1
Maximum number of concurrency per core: 10000
Maximum number of preallocated buffers per core: 10000
Receive buffer size: 8192
Send buffer size: 8192
TCP timeout seconds: 30
TCP timewait seconds: 0
NICs to print statistics:
---------------------------------------------------------------------------------
Interfaces:
Number of NIC queues: 1
---------------------------------------------------------------------------------
Loading routing configurations from : config/route.conf
Routes:
Destination: 172.16.1.0/24, Mask: 255.255.255.0, Masked: 172.16.1.0, Route: ifdx--1
---------------------------------------------------------------------------------
Loading ARP table from : config/arp.conf
ARP Table:
IP addr: 172.16.1.10, dst_hwaddr: EC:0D:9A:3A:4B:B3
---------------------------------------------------------------------------------

Checking link statusdone
[dpdk_init_handle: 263] Can't open /dev/dpdk-iface for context->cpu: 0! Are you using mlx4/mlx5 driver?
CPU 0: initialization finished.
[mtcp_create_context:1230] CPU 0 is now the master thread.
```

Here's my epserver.conf

```
# cat epserver.conf 
io = dpdk
num_mem_ch = 4
port = mlx5_1
max_concurrency = 10000
max_num_buffers = 10000
rcvbuf = 8192
sndbuf = 8192
tcp_timeout = 30
tcp_timewait = 0
```

No matter what I put as the `port` value, I always get the same behavior. The server responds to pings and trying to connect to port 80 gives `connection refused`. I was unable to find any examples of mTCP+Mellanox combo so I don't really know what to put the `port` value to.

Did I miss something?

Thank you,

Hrvoje Zeba

**Comment by hzeba** [comment]
Figured it out... putting `em2` (driver given name) did the trick. Sorry for the spam :)

**Comment by wtao0221** [comment]
Hi, @hzeba 

Do the epserver and epwget examples work correctly?

Could you please elaborate on this?

**Comment by ajamshed** [comment]
@wtao0221 

It should work. You need to put the interface name in the ``ports = `` line in th ``mtcp.conf`` file. You don't need to insert ``igb_uio.ko`` module as ``mlx`` kernel module is also dpdk-compliant.

**Comment by wtao0221** [comment]
@ajamshed 

It works now.

But the pps performance of mTCP w/ mlx5 in DPDK mode is pretty low in my test. Could you please give me some hints on it?

**Comment by ajamshed** [comment]
Can you please check whether the mTCP server works fine when you use Linux-based tcp client? Also, are you using 10 Gbps mlx5 NIC or 40/100 Gbps mlx5 NIC?

**Comment by wtao0221** [comment]
@ajamshed 

The Linux-based tcp client works fine, and the epwget w/ only one core also works fine.

Plus, I am using ConnectX-4 25 GB NIC with mlx5_core driver.

**Comment by wtao0221** [comment]
@ajamshed 

I think I have solved this problem.

Since MLNX_OFED v4.0, the RSS used in the Mellanox NIC is not symmetric. So changing both the RSS keys in mlx5 DPDK and RSS keys in the NIC just helps.

Thanks.

**Comment by ajamshed** [comment]
@wtao0221:

Can you please share the code that needs to be updated to accommodate the fix? I don't have access to the NIC that you are using. It will be useful to document/update this fix in the master branch of mTCP. Thanks!

**Comment by wtao0221** [comment]
Hi, @ajamshed 

1. Modify the default RSS keys at ```line 190``` in ```/mtcp/dpdk-17.08/drivers/net/mlx5/mlx_rxq.c``` to the RSS keys used in mTCP.
```
uint8_t rss_hash_default_key[] = {
0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05,
0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05,
0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05,
0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05,
};
```
2. ```echo "toeplitz" > /sys/class/net/$NIC_NAME/settings/hfunc``` to set the hash function to "toeplitz" as used in mTCP.

3. and use ```/opt/mellanox/ethtool/sbin/ethtool -x $NIC_NAME hkey``` to check whether step 2 takes effect.

**Comment by wtao0221** [comment]
@ajamshed 

I have tested. Just using ```ethtool``` provided by Mellanox to set rss function and rss keys can not enable mtcp w/ mln5 dpdk driver to work correctly if I do not modify the rss key in ```/mtcp/dpdk-17.08/drivers/net/mlx5/mlx_rxq.c```.

**Comment by ajamshed** [comment]
Okay thanks @wtao0221. I will contact the dpdk authors and ask why the dpdk set rss seed api function is not working.

**Comment by wtao0221** [comment]
@ajamshed 

Thanks. Look forward to your further updates.

**Comment by ajamshed** [comment]
@wtao0221,

I looked into the dpdk mlx5 driver code a bit further. It seems that the rss-key-specific code has been updated in dpdk-18.02-rc1. But the dpdk driver shows build compilation errors when  ``CONFIG_RTE_LIBRTE_MLX5_PMD`` is enabled. I will send the Mellanox driver team an email to inquire about the details.
