### ISSUE TITLE
Can mtcp run on multiprocess environment？

### ISSUE THREAD

**Issue by colinzhen** [eunyoung14/mtcp#165]
hi,
 I am trying to use mtcp in my projct, but i meet some problmes, so I am asking your help.
1. Can mtcp run on multiprocess?  In my project, one process works as 'master' and the config file is like:
    "multiprocess = 0 master". the other processes work as slave mode, the config is "multiprocess = 1".
   Can mtcp work correctly in my environment?
2. question about the 'mtcp_epoll_wait':  Can I use mtcp_epoll_wait in the threadpool? the thread works like:
  while(1)
   {
        mtcp_epoll_wait();
        ......handle the data
       mtcp_epoll_ctl(MTCP_EPOLL_CTL_MOD);
   }
  all the pthreads waits for the same 'epfd' and 'mtcp_ctx' and the EVENTS set in ET mode?
In my test, it seems it does not work, but when I change the count of theradpool to '1', it works.  I am asking your suggesstion, can I design it like this?

 Many thanks for your kind help.

**Comment by ajamshed** [comment]
colinzhen,

1- mTCP multi-process mode should run fine. Please check the README file within ``apps/example/README`` for details. And let me know if you face any issues. Also, please note that you'll need to insert static ARP entries to communicate with peers when you run applications in multi-process mode.

2- I would suggest that you stick with 1 thread for optimal performance (more threads mean more CPU cycles spent on thread scheduling). You may also run into certain race conditions if multiple threads try to access ``eventpoll`` objects simultaneously.
