### ISSUE TITLE
/mtcp/apps/apache_benchmark/server/httpd.exp': No such file or directory

### ISSUE THREAD

**Issue by wangshuaizs** [eunyoung14/mtcp#166]
hi,

i am installing ab in linux 16.04 following the instruction in apache_benchmark/INSTALL file. But when i run "sudo make install", error occured:
/usr/bin/install -c -m 644 aprutil.exp /usr/local/apache2/lib
/usr/bin/install -c -m 755 apu-config.out /usr/local/apache2/bin/apu-1-config
make[2]: Leaving directory '/home/w/mtcp/apps/apache_benchmark/srclib/apr-util'
Making install in pcre
make[2]: Entering directory '/home/w/mtcp/apps/apache_benchmark/srclib/pcre'
make[3]: Entering directory '/home/w/mtcp/apps/apache_benchmark/srclib/pcre'
make[3]: Leaving directory '/home/w/mtcp/apps/apache_benchmark/srclib/pcre'
make[2]: Leaving directory '/home/w/mtcp/apps/apache_benchmark/srclib/pcre'
make[2]: Entering directory '/home/w/mtcp/apps/apache_benchmark/srclib'
make[2]: Leaving directory '/home/w/mtcp/apps/apache_benchmark/srclib'
make[1]: Leaving directory '/home/w/mtcp/apps/apache_benchmark/srclib'
Making install in support
make[1]: Entering directory '/home/w/mtcp/apps/apache_benchmark/support'
make[2]: Entering directory '/home/w/mtcp/apps/apache_benchmark/support'
make[2]: Leaving directory '/home/w/mtcp/apps/apache_benchmark/support'
cp: cannot stat '/home/w/mtcp/apps/apache_benchmark/server/httpd.exp': No such file or directory
Makefile:18: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/w/mtcp/apps/apache_benchmark/support'
/home/w/mtcp/apps/apache_benchmark/build/rules.mk:72: recipe for target 'install-recursive' failed

anybody knows why it happened? i download the source code of ab, and i find there is no directory 'server' in mtcp/apps/apache_benchmark, while it exists in the original source code of ab.

thank you!

**Comment by ajamshed** [comment]
wangshuaizs,

Please refer to ``README-mtcp`` instead. I am sorry, but we should have been more clear on this. I will update the documentation accordingly.
