### ISSUE TITLE
Is rte_ipv4_phdr_cksum needed for hardware checksum?

### ISSUE THREAD

**Issue by particle128** [eunyoung14/mtcp#168]
Hi,

We are using mtcp in our project. During the perf measurement, we observed that `rte_ipv4_phdr_cksum` had some perf overhead.
I tried to remove this line below, and looked everything works fine. The checksum can be offloaded successfully, and the checksum value is also the same as before. 
I wonder whether `rte_ipv4_phdr_cksum` is needed? Do you have any concerns if I remove this function call completely?

The driver on my test machine is `mlx5`.

In dpdk_module.c

```c
int32_t
dpdk_dev_ioctl(struct mtcp_thread_context *ctx, int nif, int cmd, void *argp) {
...
    case PKT_TX_TCPIP_CSUM:
        ...
        m->ol_flags = PKT_TX_TCP_CKSUM | PKT_TX_IP_CKSUM | PKT_TX_IPV4;
        // tcph->check = rte_ipv4_phdr_cksum((struct ipv4_hdr *)iph, m->ol_flags); // remove this line
...
}
```

Thanks very much,
particle128

**Comment by ajamshed** [comment]
Hi particle128,

I tried disabling that line in machine that had Fortville NICs and it failed to offload checksum computation correctly. Also, please have a look at:
http://dpdk.org/doc/api/rte__mbuf_8h.html#a555401418f43fe357a838856b1e49726

It explains that you need to compute the checksum of the pseudoheader. I hope this helps.
