### ISSUE TITLE
SSL load test tool on mtcp ?

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#17]
Hi

the ported apachebench does not support SSL load test, I am wondering what client SSL load tool mtcp project used to evaluate SSLShader performance mentioned in the paper. I am interested to know if there is existing one or get some idea on how to port one on mtcp.

Thanks

**Comment by eunyoung14** [comment]
Hi, 
We internally have openssl-0.9.8w ported for mTCP, but it is not maintained since the dpdk update. If you want, we can open the source code of it.
By the way, we didn't test SSL with mtcp-lighttpd, because SSLShader worked as SSL proxy and ligghtpd didn't need to handle SSL.

**Comment by vincentmli** [comment]
yes, could you please open the source code of it, I will get better idea how you guys ported it for mTCP.

**Comment by eunyoung14** [comment]
I'll make it available in this github soon.

**Comment by vincentmli** [comment]
that is great, thank you!

**Comment by eunyoung14** [comment]
mtcp-openssl has been made available in the latest commit.

**Comment by eunyoung14** [comment]
I think the committed version was not the right one, so I reverted it back. However, we were also able to test SSLShader with normal ab which worked with openssl. Please consider using it. When testing SSL, clients's network stack usually does not become a bottleneck because the most of the CPU cycles are consumed by cryptographic operations.

**Comment by vincentmli** [comment]
"normal ab" means _not_  the ab ported from mTCP? yes, I know the ab from apache works with ssl, but the ported ab in mTCP doesn't, I couldn't find compile option to enable the ported ab with ssl, the ab coming from apache has '--enable-ssl' option, the ported ab doesn't. my intention is to using ported ab as SSL load test tool as well.  thank you for your time for the confusion I caused

**Comment by vincentmli** [comment]
I copied ssl portion of configure script from httpd-2.2.24 into the ported apache bench configure script and the sub directory modules/ssl, I am able to compile the ported ab with ssl support, but it appears the ab code has not been completely modified to support mTCP, my test shows after TCP three way handshake, no subsequent SSL handshake, so the ported ab code may need to be modified to support SSL request, is there clue on how I can change the ab code

**Comment by ajamshed** [comment]
Vincent,

I am sorry if we have misled you earlier. For the mTCP paper, the SSLShader experiment was conducted using the default version of ab (the one that was not ported to mTCP). As Eunyoung mentioned, the bottleneck for this experiment was not ab. We do not have the complete mTCP version of ab at the moment. We neither have immediate plans to port the library. However, we may consider working on it if more users ask for it.

**Comment by vincentmli** [comment]
thanks, I understand you guys has priorities and out of man power,  I am willing to help porting ab with SSL support, I just need some clue from you guys on how to port it properly.  I traced the code to where it fails in ab as below in testMain function of ab:

1919 #ifdef USE_SSL
1920                         if (c->ssl) {
1921                             ssl_proceed_handshake(c);
1922                         }
1923                         else
1924 #endif

 609 static void ssl_proceed_handshake(struct connection *c)
 610 {
 611     int do_next = 1;
 612
 613     while (do_next) {
 614         int ret, ecode;
 615         apr_pollfd_t new_pollfd;
 616
 617         ret = SSL_do_handshake(c->ssl);
 618         ecode = SSL_get_error(c->ssl, ret);
 619

and it fails SSL_do_handshake, so you mean I have to port openssl library to make SSL_do_handshake works? or just ab.c code. 

if you can give me some guidance on which library/code should be changed to make it work, I am willing to try :).

**Comment by eunyoung14** [comment]
I think you'll need to port openssl library as well. We ported ab to use the "mtcp sockets", which should be only used with mTCP API. Since ab uses openssl library, you will need to change the parts that socket operations take place in openssl.
As a reference, you may look at the differences we made to ab. The code we touched are support/ab.c and the apr library code in srclib/apr. grep with the keyword "mtcp" will help you figuring out the difference.

**Comment by vincentmli** [comment]
Thanks for the clue. I have a patch for ab to work with SSL on top of mTCP. I basically copy/paste OpenSSL crypto/bio/bss_sock.c code  and rename a new bio for mTCP in ab.c, so there is no need to patch OpenSSL library to build with mTCP like you guys did with libapr. just build ab.c linking with openssl should work. do you want to take the patch?
