### ISSUE TITLE
Support for connect() functionality

### ISSUE THREAD

**Issue by uttampawar** [eunyoung14/mtcp#170]
We have enabled mTCP+DPDK stack for Node.js. In our experiement we have a server application built with mtcp+dpdk stack which works ok. But there is another scenario where it connects to a database server (acting as a client) which doesn't work. To make it work, we have hardcoded as follows after mtcp_init_wrapper() call in the node.js runtime.

int node_mtcp_init_wrapper() {
  ...
  ...
  mtcp_init();
  mtcp_create_context(cpu);
  ...
    /* Need when node application acts as a client - 'for e.g. connecting to mongodb' */
    in_addr_t daddr = inet_addr("192.168.1.3"); /* we have mongodb server listening at specific ip+port addr */
    in_port_t dport = htons(27017);
    mtcp_init_rss(mctx, INADDR_ANY, 1, daddr, dport);
    ...
    return ret;
}

It makes sense to provide that behind the scene as part of connect() call.

**Comment by ajamshed** [comment]
Thanks @uttampawar for the suggestion. I will work on this issue soon.

**Comment by ajamshed** [comment]
``mtcp_connect()`` can now handle ``mtcp_init_rss()`` logic internally.
