### ISSUE TITLE
Simplifying recv and send buffer size in the configuration

### ISSUE THREAD

**Issue by uttampawar** [eunyoung14/mtcp#171]
Since recv and send buffer size needs to be same, we can simplify by specifying only one variable for e.g. recvbuf=16384, and mtcp should use that same for sndbuf avoiding conflicting values in the conf file.

**Comment by ajamshed** [comment]
I think maintaining different buffer size thresholds for send and recv will be better in the long run. There are some applications that may have different requirements e.g. keeping send buffer sizes larger than recv buffer sizes and vice versa. Linux networking modules also allow users to modify buffer sizes separately (e.g. ``/proc/sys/net/ipv4/tcp_rmem``, ``/proc/sys/net/ipv4/tcp_wmem``).

**Comment by uttampawar** [comment]
@ajamshed I was thinking that user need to specify them only if they are different, otherwise one value should be suffice. Does that make sense?

**Comment by ajamshed** [comment]
I will make the change in my next commit.
