### ISSUE TITLE
Simplify config file for master and slave processes

### ISSUE THREAD

**Issue by uttampawar** [eunyoung14/mtcp#172]
Currently in a case where master and slave processes are involved we are using two config files, one each for master and slave process. I've following example,
$ cat master.conf
io = dpdk
num_mem_ch = 4 
multiprocess = 0 master
port = dpdk0
max_concurrency = 8192
max_num_buffers = 8192
rcvbuf = 16384
sndbuf = 16384
tcp_timeout = 30
tcp_timewait = 0 
stat_print = dpdk0

$ cat slave.conf
io = dpdk
num_mem_ch = 4 
multiprocess = 1 
port = dpdk0
max_concurrency = 8192
max_num_buffers = 8192
rcvbuf = 16384
sndbuf = 16384
tcp_timeout = 30
tcp_timewait = 0 
stat_print = dpdk0

Instead of having 2 separate files, can we have only one file with one variable as "multiprocess = 1" indicating multiprocess mode. So whoever starts the first process becomes the master process and subsequent processes should automatically becomes slave processes by querying internal state (if there is such a way). 
In fact we can take it further by specifying "multiprocess = 0" as default making it into just one conf file for single mode execution and with simple change "multiprocess = 1", we can enable multi-process mode.
This will help considerably to the end user by reducing maintenance of config files.

**Comment by ajamshed** [comment]
It is done. Please see ``apps/example/README`` for details.
