### ISSUE TITLE
how to use xxxxxxStats print information?

### ISSUE THREAD

**Issue by keil-chan** [eunyoung14/mtcp#174]

**Comment by ajamshed** [comment]
Can you please elaborate more on your question? Statistics are printed per second whenever you run an mTCP application. You can disable this feature by commenting out the NETSTAT macro from the Makefile. Let me know if you have any follow-up questions.

**Comment by keil-chan** [comment]
first thx！
i mean, NETSTAT is used in my Makefile but not statistics.

**Comment by ajamshed** [comment]
Please make sure you have ``stat_print`` line enabled (uncommented) in the conf file.

**Comment by keil-chan** [comment]
thx！
stat_print line is there.
file: src/config.c, line: 559, strcmp(CONFIG.eths[i].dev_name, q) == 0, return < 0. in fact, both "CONFIG.eths[i].dev_name" and "q" are "dpdk0". i use function 'strncmp' no problem.
