### ISSUE TITLE
Why bind <sip, sport, dip, dport> to a core via GetRSSCPUCore?

### ISSUE THREAD

**Issue by fomy** [eunyoung14/mtcp#176]
mtcp_connect will bind a <sip, sport, dip, dport> to a core.

For example,

```
	rss_core = GetRSSCPUCore(socket->saddr.sin_addr.s_addr, dip, 
				 socket->saddr.sin_port, dport, num_queues, endian_check);
	
	if (rss_core != mctx->cpu) {
		errno = EINVAL;
		return -1;
	}
```

Anyone can tell me the reason?

Thanks
Min

**Comment by ajamshed** [comment]
Hi fomy,

Please see the man page of [mtcp_init_rss()](http://shader.kaist.edu/mtcp/man/mtcp_init_rss.html). The `if` condition is checking whether the <sip,dip,sport,dport> tuple chosen is right for the current CPU core (mctx->cpu).

**Comment by fomy** [comment]
Hi ajamshed,

We are using mtcp+dpdk in multi-process mode, and each process has a single core/mctx.
Our application has 2 servers with 4 processes, such as:
> server1-process1 (mtcp client, core=1, ip=10.0.0.1, port=20000)
> server1-process2 (mtcp server, core=2, ip=10.0.0.1, port=30000)
> server2-process1 (mtcp client, core=1, ip=10.0.0.2, port=20000)
> server2-process2 (mtcp server, core=2, ip=10.0.0.2, port=30000)

and each mtcp clients need to connect to both mtcp servers.
We use two rte_ring instead of the rx/tx queue for the connection between the two process in the same server. 

But when we bind the addr for the mtcp client, we get an error from the RSS checking.
Could we ignore this error in our application?

Thanks,
Min

**Comment by ajamshed** [comment]
Hi fomy,

If you are seeing an RSS checking error, then it is most likely the case that your client is picking an incorrect source port number. This means that the SYN-ACK packet that will return back to the client may end up on a different RSS queue (i.e. you will fail to establish a TCP handshake). One way to avoid this problem is that you don't bind the client with any source port. Can you re-design your program to accommodate this change?

**Comment by fomy** [comment]
Hi ajamshed,

Because each process has its own rx queue, we bind a port for the client to enable dpdk flow director.
Will it work?

Min

**Comment by ajamshed** [comment]
If you are using an Ethernet flow director, you can ignore the rss warning.

**Comment by fomy** [comment]
Thanks
