### ISSUE TITLE
mtcp do not retransmit Fin pkts?

### ISSUE THREAD

**Issue by simpx** [eunyoung14/mtcp#183]
After Fin pkt is sent, sender enters the FIN-WAIT-1 state

sender will not retransmit Fin pkt if it is loss

`sndvar->is_fin_ackd` is defined but not used

**Comment by ajamshed** [comment]
@simpx,

The logic for retransmissions of ``FIN`` packets is present in ``timer.c`` (lines 311-331). I understand that ``sndvar->is_fin_ackd`` is not being used (maybe one of my co-authors initially added this field.. but then realized that this is not needed). Probably a wireshark/tcpdump analysis would be help more to prove this conjecture.
