### ISSUE TITLE
Macro TRACE_DBG not work

### ISSUE THREAD

**Issue by wtao0221** [eunyoung14/mtcp#194]
Hi,

I have uncomment ```DBG_OPT``` in ```mtcp/src/Makefile``` and recompile mTCP and example app.

But, there is still no debug-related output in ```log_*``` file.

**Comment by wtao0221** [comment]
BTW, there are logs related to ```EPOLL```, ```STATE``` and ```STREAM```.

**Comment by ajamshed** [comment]
@wtao0221:

Please make sure that the line ``GCC_OPT += $(DBG_OPT)`` is also included in the ``Makefile``. I just tried uncommenting lines 27-30 of the ``Makefile`` and then I recompiled mTCP ``src`` and ``example apps``. I could see debug statements being printed in the ``log_*`` files.

**Comment by wtao0221** [comment]
Hi, @ajamshed 

Thanks for your reply.

I have checked ```Makefile``` and there are some output in the ```log_*``` files.

For example, I use ```TRACE_DBG("Hello")``` in the program. But, there are no ```Hello``` being printed in the log files.

**Comment by wtao0221** [comment]
I know what's going wrong, thank you.
