### ISSUE TITLE
mtcp with openNetVM: Error in arp.conf: more entries than are specifed,

### ISSUE THREAD

**Issue by SSam009** [eunyoung14/mtcp#205]
Hello, 

I am trying to run mTcp over openNetVM.  Example application  epserver failing with " Error in arp.conf: more entries than are specifed," error.  Did I miss any configuration step? 

Here is epserver output 
--------------------------------------------------------------------------------------------
[root@testhost example]# ./epserver  -p /root  -f epserver.conf -N 1   
Configuration updated by mtcp_setconf().
---------------------------------------------------------------------------------
Loading mtcp configuration from : epserver.conf
Loading interface setting
EAL: Detected 28 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1572 net_i40e
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1572 net_i40e
cur_index:1, action:2, destination:1

APP: Waiting for manager to assign an ID...
APP: Using Instance ID 4
APP: Using Service ID 1
APP: Finished Process Init.
Configurations:
Number of CPU cores available: 1
Number of CPU cores to use: 1
Maximum number of concurrency per core: 10000
Maximum number of preallocated buffers per core: 10000
Receive buffer size: 8192
Send buffer size: 8192
TCP timeout seconds: 30
TCP timewait seconds: 0
NICs to print statistics:
---------------------------------------------------------------------------------
Interfaces:
Number of NIC queues: 1
---------------------------------------------------------------------------------
Loading routing configurations from : config/route.conf
fopen: No such file or directory
Skip loading static routing table
Routes:
(blank)
---------------------------------------------------------------------------------
Loading ARP table from : config/arp.conf
Error in arp.conf: more entries than are specifed, entry=10.0.0.4/32 3c:fd:fe:a3:f1:59
[root@testhost  example]# 

[root@testhost example]# cat config/arp.conf
# This file is to configure static arp tables.
# Rename this file to arp.conf and set the appropriate values.
# Please save this file as config/arp.conf. Put the config/
# directory in the same directory where the binary lies.
#
# (Destination IP address/IP_prefix) (Destination MAC address)
10.0.0.4/32 3c:fd:fe:a3:f1:59
[root@testhost example]#

**Comment by ajamshed** [comment]
Please see if the total number of entries present in ``arp.conf`` match the ``ARP_ENTRY`` macro value. It looks like there is a mismatch.

**Comment by SSam009** [comment]
@ajamshed  Sorry, It's my mistake.  ARP_ENTRY is not matching.   I was able to run the example application.
