### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by sequoiar** [eunyoung14/mtcp#21]
Is there any plan to support UDP? If no, can you tell me the start point to add UDP.

**Comment by ajamshed** [comment]
Hi, 

There are no immediate plans to provide support for UDP. I would recommend that you look at ip_in.c 
(ProcessIPv4Packet()) function. You can create a new switch case for IPPROTO_UDP and create a module udp_in.c to get things started.

**Comment by ppnaik1890** [comment]
Hi @ajamshed ,
Does mTCP currently support UDP? or is there any patch available for it. 
Thanks!
