### ISSUE TITLE
How to inspect the detailed log?

### ISSUE THREAD

**Issue by wtao0221** [eunyoung14/mtcp#24]
Dear all,

Is there a way to inspect the detailed log? Since the output of the example just shows the number of errors, I do not know what is wrong.

Thanks,
Tao

**Comment by vincentmli** [comment]
in mtcp/src/Makefile, you can uncomment #DBG_OPT and recompile mtcp and example app, then you will get more detail debugging output in log_<thread/cpu_id> for each mtcp thread

**Comment by wtao0221** [comment]
Thanks, Vincent.

But I have get into another trouble. When I am running the example of
epserver and epwget. The epwget cannot wget the content of the remote
server which is running epserver. (ps: I am sure that the connection is
established)

Best,
Tao

**Comment by vincentmli** [comment]
can you use epwget to access a another webserver say apache or nginx? I assume you run epwget and epserver on different machine with DPDK and mTCP installed.

**Comment by wtao0221** [comment]
Yep,

mTCP does not work in this situation?

Best,
Tao

**Comment by vincentmli** [comment]
I am able to get epserver to work when using curl as client from another Linux machine, have not tried to use epwget with epserver, but I see no reason why it should not work, so I would make sure you can get epserver work with other http client like curl.

**Comment by arunkumarsit** [comment]
Hi Vicent,

I faced the exact issue faced by Tao Wang. The epwget client running in
different host is not connecting to epserver in another host.
But legacy wget is working fine. There seems to be some issues with the
epwget application which needs to be checked upon.

Thanks,
Arun

**Comment by ajamshed** [comment]
Hi,
I apologize for the delay. Can you please tell us the IP addresses you assigned for the client
and the server. We would also like to know the arp.conf/route.conf file contents (if you were using
any) for epwget. What was the exact command-line arguments you were using to run epwget?
Finally, were you running epwget in a VM? Just FYI: we haven't enabled the mTCP in virtualised
environment yet.

**Comment by arunkumarsit** [comment]
Hi Asim,
Sorry for the late reply from my side. It seems the issue is with the GRUB configuration.

I found that missing GRUB entry makes this issue. Please add following line in "/etc/default/grub" file.
**GRUB_CMDLINE_LINUX_DEFAULT="iommu=pt, intel_iommu=on"**

Then do "update-grub" and reboot host. This should solve the issue.

Note: Due to system dependency I cannot test epwget as of now with epserver.

Thanks,
Arun

**Comment by ajamshed** [comment]
Hi Arun,

I am glad the issue is resolved. In the future, it will be better if you try example dpdk applications before testing mTCP stack + apps. This would help us narrow down the issue more efficiently.

**Comment by arunkumarsit** [comment]
Agreed 😀
