### ISSUE TITLE
KNI support in mTCP 

### ISSUE THREAD

**Issue by arunkumarsit** [eunyoung14/mtcp#26]
Hi mTCP team,

I am trying to integrate KNI (Kernel NIC interface) support into mTCP code.
Wanted to know whether KNI interface is already supported in newer version ?
Why KNI is not considered before, even for UDP packets? Is it a good idea to add KNI support ?

As I am trying to add KNI support, kindly let me know the places of doing code changes inside epserver application.

Thanks,
Arun

**Comment by ajamshed** [comment]
Hi Arun,

I last checked up on KNI several months ago when I was testing dpdk-1.8.0. At that time, KNI did not look like a good fit for mTCP as the packet context (sk_buff) is created inside the kernel. One of our goals in mTCP is to make packets completely bypass the kernel and allow more CPU resources to be spent on the user space application. I have not gone through the KNI design in recent versions but I was not expecting any massive change in the architecture. Why do you think it is a good idea to add KNI support?

**Comment by arunkumarsit** [comment]
I definitely agree with you. The performance and the user space packet handling are the things we need using mTCP. But how about handling any unsupported packet types (UDP).

I am in the process of integrating NFS Ganesha (user space NFS application) server with mTCP support. But NFS server supports UDP traffic as well, so I need to support UDP streams as well. I decided Kernel networking stack to handle the UDP packets in order to avoid developing UDP parser in user space.
Also whether mTCP handles RPC requests for **mount** commands? Up to my knowledge I feel like, RPC calls also needs to be sent to Kernel for processing.

As per the KNI example application (I checked it in dpdk-2.0.0), KNI application receives the input packets from eth port and sends it to KNI queue (via **rte_kni_tx_burst**) and then it will be sent to networking stack via netif_rx(() call.
While doing tx, the packets will be received by KNI queues (**rte_kni_rx_burst**) and the same will be sent out via eth ports (**rte_eth_tx_burst**)

Let me know your views/suggestions on this.

**Comment by ajamshed** [comment]
I will probably have to (i) discuss the design in more detail with you, and (ii) look at KNI API + design in further detail. :). UDP is not supported in the mTCP stack. But I am not sure what will be the best design to integrate NFS Ganesha with mTCP. Let's discuss this further in email.. Shall we?

**Comment by quadrat** [comment]
Hi everybody.

Has there been any progress in the plan to support KNI?

I want to create a emulation environment based on Mininet with a number of HTTP servers running on Mininet hosts inside a single Linux kernel. There are be no physical interfaces involved. While I would like to implement these servers based on mTCP, I am afraid there is currently no existing possibility to connect mTCP apps to virtual Mininet network interfaces in kernel space. I assume that the usage of KNI would make this possible?

Any other ideas how to achieve this are welcome, too!

**Comment by arunkumarsit** [comment]
Hi quadrat,

I integrated the KNI interface support with mTCP application (specifically in dpdk_module.c file) and KNI is working as expected.
But after this integration, there are 2 interfaces dpdk0 (mtcp) and vEth0_0 (KNI interface) are available for the same NIC interface. I am currently checking on this.

**Comment by arunkumarsit** [comment]
Hi Asim Jamshed,

I have successfully integrated KNI with mtcp application. So using KNI I am able to send only needed packets to kernel networking stack.
After receiving packets via "rte_eth_rx_burst()" DPDK call, I can parse the packet and decide whether to send it to Kernel stack or let the mtcp to process.
Most part of the integration is done in dpdk_module.c and io_module.c files.

Note that I had to disable the dpdk0 interface and has to bring up KNI interface (say vEth0) to enable the above operation (after the application intialization is done).

**Comment by ajamshed** [comment]
Hi Arun,

I am happy to know that you have made KNI support operational with your setup. Would you mind sharing the code? We get requests for this type of extension from others as well. It will be great if your patch can be integrated in the main mTCP stack.

**Comment by arunkumarsit** [comment]
Hi Asim, I have sent you a mail on this. we will discuss in mail further.

**Comment by tigerjibo** [comment]
Hi Arun:
   Can you share your code(KNI support in mTCP) to me? Thanks for you in advance!
