### ISSUE TITLE
About mtcp_setsockopt

### ISSUE THREAD

**Issue by wtao0221** [eunyoung14/mtcp#28]
Hi, mTCP team,

Can we set other tcp options like tcp_nodealy in mTCP?

Best,
Tao

**Comment by eunyoung14** [comment]
Hi Tao,

Nagle's algorithm in TCP is not implemented in mTCP. All the data given from the user will be served asap if the network  is not congested. So, it will be like tcp_nodelay turned on by default.
As you see in the mtcp/src/api.c, mtcp does not implement changing socket options using mtcp_setsockopt(). Only a few arguments are implemented in mtcp_getsockopt() as well. If you are going to implement some tcp options, the above two functions will be good starting points.

EunYoung
