### ISSUE TITLE
How to modify epwget to create connection to multiple destination ip addresses?

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#29]
Hi,

I have a need to make epwget to create tcp connections to multiple destination ip addresses to simulate request to a wildcard network listener like 0.0.0.0:80.  

reading the code, the "host" is parsed from command input argv[1] and passed on to "daddr" in main().

then in RunWgetMain, in the  while (!done[core]) loop, "daddr" is passed on to CreateConnection.

can I  increment destination ip address 'daddr' in  while loop below before CreateConnection(ctx) to achieve that? 

<pre>
572                 while (ctx->pending < concurrency && ctx->started < ctx->target) {
573                         if (CreateConnection(ctx) < 0) {
574                                 done[core] = TRUE;
575                                 break;
576                         }
577                 }
</pre>
is there anything I might be missing?  I noticed the mtcp_init_rss has "daddr" as input already to CreateAddressPoolPerCore before the while (!done[core]) loop, 

I also read there is "primary" and "secondary" processes in DPDK that user can start two identical processes, say  start two epwget processes, but that seems not supported in mTCP.

I would appreciate any input, thanks!

**Comment by vincentmli** [comment]
I have read more mTCP code and it looks to me when mtcp_connect gets called, the src ip, src port, dst ip, dst port are picked up from address pool mtcp->ap, which is initialized in mtcp_init_rss->CreateAddressPoolPerCore(mctx->cpu, num_cpus,saddr_base, num_addr, daddr, dport);

it appears when daddr changes, a different mtcp->ap is required, is that true? does it mean the field 'addr_pool_t ap'  in structure mtcp_manager needs to be modified to be an array or hash table indexed by 'daddr', this is one idea I have in my mind

<pre>
struct mtcp_manager
{
        addr_pool_t ap;                 /* address pool */
}
</pre>

another idea I have in mind is in CreateAddressPoolPerCore, remove the 'daddr' parameter as one of the factor, which is  passed on to   GetRSSCPUCore and GetRSSHash too. this seems easier and less invasive changes, but I am not sure if this would work when 'daddr' is removed.

Do I make any sense?

**Comment by vincentmli** [comment]
I tried to remove 'dip' from GetRSSHash, this appears result in DPDK driver dropping SYN+ACK packet from target server as the DPDK driver may require "destination ip" for RSS to work properly. so it appears the idea of removing "daddr" from CreateAddressPoolPerCore does not work.

<pre>
+/*
        for (i = 0; i < 32; i++) {
                if (dip & MSB32)
                        res ^= key_cache[32+i];
                dip <<= 1;
        }
+*/
</pre>

**Comment by vincentmli** [comment]
disable RSS in DPDK (set mq_mode to ETH_MQ_RX_NONE instead of  ETH_MQ_RX_NONE kind of workaround the packet dropping issue, but then it disable the multi receive queue feature and only one queue can receive packet. 

mtcp/src/dpdk_module.c
<pre>
 75 static struct rte_eth_conf port_conf = {
 76         .rxmode = {
 77                 .mq_mode        =       ETH_MQ_RX_NONE,

..........
</pre>

**Comment by vincentmli** [comment]
I sort of hacked mTCP to achieve what I want to target on multiple destination addresses http://ickernel.blogspot.com/2016/01/syn-flood-network-virtual-server-in.html. close the issue

**Comment by ajamshed** [comment]
Thanks for the update. I realise that we need to support multiple source IP addresses. mtcp_init_rss()
is seriously restricting this feature. I will think about how we can accommodate this...
