### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by pm-kartik-sura** [eunyoung14/mtcp#3]
I wanted to ask the following questions:
1. After installing mtcp, does the applications run without code change?
2. What are the code changes(if any)?

Background: We have a fastcgi-webserver which runs on apache/nginx. I have seen an apache example in the apps folder. Is it a modified version to support mtcp?

If i use this apacha, do i just need to deploy my fastcgi module (and thats it?)

**Comment by ajamshed** [comment]
1. You will have to make a few changes to the application to incorporate the mTCP stack. But these changes will be small: the mTCP socket interface resembles BSD sockets API. For example, to create a socket you will have to call mtcp_socket(...) function call, and so on..

2. We suggest you to have a look at README.devel file.

The *Apache benchmark (ab)* is patched up and supports mTCP. However, the makefile currently needs a makeover (which I plan to do the next time I get free). We have not focused on apache or nginx so far but we do provide an mTCP-enabled lighttpd.
