### ISSUE TITLE
Can mTCP support DPDK virtio and runs in KVM guest?

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#31]
Hi,
I looked at mtcp/src/dpdk_module.c, port_conf, rx_conf, tx_conf are more tuned for physical Intel drivers, but the function dpdk_send_pkts and dpdk_recv_pkts calls common DPDK API rte_eth_tx_burst, rte_eth_rx_burst respectively. 

I assume the common DPDK API rte_eth_tx_burst could eventually calls  virtio_xmit_pkts, and rte_eth_tx_burst calls virtio_recv_pkts when librte_pmd_virtio is loaded in KVM guest.I could very likely miss something, I am guessing mTCP should work in KVM guest given some port_conf, rx_conf, tx_conf tuning for virtio in dpdk_module.c. 

could you give me some guidance what code needed to be added/changed to support mTCP runs in KVM guest with virtio PMD?

here is the DPDK virtio PMD usage link http://dpdk.org/doc/guides/nics/virtio.html

Vincent

**Comment by vincentmli** [comment]
or can mTCP run on VF port of  SR-IOV in KVM guest as http://dpdk.org/doc/guides/nics/intel_vf.html

**Comment by jagsnn** [comment]
As far as I understand mTCP uses standard DPDK 2.1.0 with minor tweaking to update stats of DPDK interface back into Linux Kernel. 

DPDK works on KVM guests with interfaces coming in from host OS either as Direct Passthrough [ Physical interface or Virtual interface (Virtual Function)], Emulated interfaces (e1000), and Virtio interfaces (with or without vhost backend support).

So as such mTCP should be using the standard rx, tx functions of DPDK, and dpdk will internally take care of loading which ever interface driver functions it has to used based on the type of interface.

First, If the explicit bind of the concerned interfaces into igb_uio using dpdk's setup.sh is happening properly, then on running mtcp with dpdk, those interfaces bound to the igb_uio will be picked by dpdk without any problem.

So I don't see any changes you would need to do for running mTCP on VF port of SR-IOV in KVM guest.

First, just make sure your interface in Guest is visible using "lspci", "ifconfig".
Second using DPDK's ./tools/setup.sh you are able to bind it to igb_uio driver.

If you are able to bind it with the second step, then things should work in mtcp without any much change is what I think.

**Comment by ajamshed** [comment]
Hi Vincent,

I plan to resume mTCP maintenance work from next month. mTCP needs some minor bug fixes. I will then move on to stabilising netmap support before I tackle virtualisation support. I second what jagsnn has written. I will put up the necessary documentation for enabling virtualisation support once everything is all set.

**Comment by congnguyenthe** [comment]
Hi there,

This is just the same as my problem now. Currently I'm trying to run mTCP with virtio-pci-net on KVM guest, I can build, bind card using setup.sh script without any errors, however, when I try to run mTCP app(for example: epserver), it seems that the app could not detect the virtio card and always report that "No Ethernet Port!". It works fine with e1000 though. Any ideas or solutions are appreciate.

Thanks.

**Comment by ajamshed** [comment]
Hi,

We have discussed providing virtualization support to mTCP. Our target is to reduce the involvement of kernel (wherever possible). One of our mTCP developers was able to get mTCP ported to QEMU VM using dpdk-ovs (https://github.com/01org/dpdk-ovs/blob/development/docs/00_Overview.md). I think we will try to get the port done this way (unless someone has a better idea). As soon as I find time... :), my plan is to first update documentation and then move on to dpdk-ovs.
