### ISSUE TITLE
undefined reference to `numa_max_node'

### ISSUE THREAD

**Issue by liuzhongzhu** [eunyoung14/mtcp#34]
../../mtcp/lib/libmtcp.a(cpu.o): In function `mtcp_core_affinitize':
cpu.c:(.text+0xa1): undefined reference to`numa_max_node'
cpu.c:(.text+0xe6): undefined reference to `numa_bitmask_alloc'
cpu.c:(.text+0x13c): undefined reference to`numa_bitmask_setbit'
cpu.c:(.text+0x146): undefined reference to `numa_set_membind'
cpu.c:(.text+0x150): undefined reference to`numa_bitmask_free'

**Comment by ajamshed** [comment]
Do you have libnuma installed in your system?

**Comment by liuzhongzhu** [comment]
Is suse11sp3, Change to ubuntu12.0.4 success.
