### ISSUE TITLE
mTCP VMware vmxnet3  adapter support

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#35]
Hi,

I am running ubuntu 14.04 as virtual guest on VMware ESXi, the guest is using adapter vmxnet3. I had following diff to mtcp/src/dpdk_module.c to make mTCP compile and run, but at the web server side when I run tcpdump, I see no packet coming in to server. I don't have access to VMware ESXi hypervisor, so not sure if the packet has egressed out hypervisor. 

`diff --git a/mtcp/src/dpdk_module.c b/mtcp/src/dpdk_module.c
index 33d349e..666dfd3 100644
--- a/mtcp/src/dpdk_module.c
+++ b/mtcp/src/dpdk_module.c
@@ -57,8 +57,8 @@
 /*
- Configurable number of RX/TX ring descriptors
  */
  -#define RTE_TEST_RX_DESC_DEFAULT       128
  -#define RTE_TEST_TX_DESC_DEFAULT       128
  +#define RTE_TEST_RX_DESC_DEFAULT       128
  +#define RTE_TEST_TX_DESC_DEFAULT       512
  
  static uint16_t nb_rxd = RTE_TEST_RX_DESC_DEFAULT;
  static uint16_t nb_txd = RTE_TEST_TX_DESC_DEFAULT;
  @@ -124,7 +124,7 @@ static const struct rte_eth_txconf tx_conf = {
       \* As the example won't handle mult-segments and offload cases,
       \* set the flag by default.
       */
  -       .txq_flags =                    0x0,
  -       .txq_flags =                    ETH_TXQ_FLAGS_NOOFFLOADS|ETH_TXQ_FLAGS_NOMULTSEGS,
    };
  
  struct mbuf_table {
  `

I noticed the dpdk0 interface has empty MAC address as below:

4: dpdk0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff <==========EMPTY MAC ADDRESS
    inet 10.1.72.28/24 brd 10.1.72.255 scope global dpdk0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe00:0/64 scope link
       valid_lft forever preferred_lft forever

I reviewed dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h, noticed only IXGBE and IGB adapter were supported for mTCP to retrieve and attach MAC addresses for dpdk0 in Linux world. 

do you think the empty MAC address for dpdk0 is the reason I see no packet from the server side?

if so, adapter vmxnet3 can be added to igb_uio.h like IGB adapter to resolve the issue?

below is the output I think relevant:

EAL:   probe driver: 15ad:7b0 rte_vmxnet3_pmd
EAL:   PCI memory mapped at 0x7ff74ea00000
EAL:   PCI memory mapped at 0x7ff74ea01000
EAL:   PCI memory mapped at 0x7ff74ea02000
PMD: eth_vmxnet3_dev_init():  >>
PMD: eth_vmxnet3_dev_init(): Hardware version : 1
PMD: eth_vmxnet3_dev_init(): UPT hardware version : 1
PMD: eth_vmxnet3_dev_init(): MAC Address : 00:50:56:86:10:76
Total number of attached devices: 1
Interface name: dpdk0
Configurations:
Number of CPU cores available: 4
Number of CPU cores to use: 4
Maximum number of concurrency per core: 10000
Maximum number of preallocated buffers per core: 10000
Receive buffer size: 8192
Send buffer size: 8192
TCP timeout seconds: 30
TCP timewait seconds: 0
## NICs to print statistics: dpdk0

Interfaces:
name: dpdk0, ifindex: 0, hwaddr: 00:00:00:00:00:00, ipaddr: 10.1.72.28, netmask: 255.255.255.0
## Number of NIC queues: 4

Loading routing configurations from : /etc/mtcp/config/route.conf
Routes:
Destination: 10.1.72.0/24, Mask: 255.255.255.0, Masked: 10.1.72.0, Route: ifdx-0
## Destination: 10.1.72.0/24, Mask: 255.255.255.0, Masked: 10.1.72.0, Route: ifdx-0

Loading ARP table from : /etc/mtcp/config/arp.conf
ARP Table:
## IP addr: 10.1.72.17, dst_hwaddr: 00:23:E9:64:C0:03

Initializing port 0... PMD: vmxnet3_dev_configure():  >>
PMD: vmxnet3_dev_rx_queue_setup():  >>
PMD: vmxnet3_dev_rx_queue_setup():  >>
PMD: vmxnet3_dev_rx_queue_setup():  >>
PMD: vmxnet3_dev_rx_queue_setup():  >>
PMD: vmxnet3_dev_tx_queue_setup():  >>
PMD: vmxnet3_dev_tx_queue_setup():  >>
PMD: vmxnet3_dev_tx_queue_setup():  >>
PMD: vmxnet3_dev_tx_queue_setup():  >>
PMD: vmxnet3_dev_start():  >>
PMD: vmxnet3_rss_configure():  >>
PMD: vmxnet3_setup_driver_shared(): Writing MAC Address : 00:50:56:86:10:76
PMD: vmxnet3_disable_intr():  >>
PMD: vmxnet3_dev_rxtx_init():  >>
rte_eth_dev_config_restore: port 0: MAC address array not supported <=====here
done:

Checking link statusdone
Port 0 Link Up - speed 10000 Mbps - full-duplex
Configuration updated by mtcp_setconf().
CPU 0: initialization finished.
[mtcp_create_context:1173] CPU 0 is now the master thread.
[CPU 0] dpdk0 flows:      0, RX:      10(pps) (err:     0),  0.00(Gbps), TX:       0(pps),  0.00(Gbps)
[ ALL ] dpdk0 flows:      0, RX:      10(pps) (err:     0),  0.00(Gbps), TX:       0(pps),  0.00(Gbps)
Thread 0 handles 1 flows. connecting to 10.1.72.17:80
[CPU 0] dpdk0 flows:      1, RX:      25(pps) (err:     0),  0.00(Gbps), TX:       2(pps),  0.00(Gbps)
[ ALL ] dpdk0 flows:      1, RX:      25(pps) (err:     0),  0.00(Gbps), TX:       2(pps),  0.00(Gbps)

**Comment by vincentmli** [comment]
also when adding the guest from vmwahre vsphere client, the network label is applied (vlan tagging in ESXi)

I just realized the message below is because vmxnet3 pmd driver did not implement mac_addr_add function in vmxnet3 dev_ops, is that possible reason to cause packet drops?

rte_eth_dev_config_restore: port 0: MAC address array not supported

**Comment by vincentmli** [comment]
I did a test on physical working box to verify if "rte_eth_dev_config_restore: port 0: MAC address array not supported" to be the cause, it isn't. I got same debug log line with ixgbe adapter after manually modifying  rte_eth_dev_config_restore to not restore the MAC address to hardware and get same debug output as "rte_eth_dev_config_restore: port 0: MAC address array not supported". but the test on physical box continues working.

so it is something else, now I have two suspect left:

1, the vlan tagging in ESXi
2.lack of vmxnet3 support in mTCP igb_uio for stats and MAC retrieve and attach to netdev in Linux (seems unlikely)

any other clue would be helpful.

Thanks!

**Comment by vincentmli** [comment]
I made some progress on this issue, after migrating the target VM to the same ESXi host running mTCP VM, the packet from epwget passed through,  so the packet would not pass through physical switch but just within same ESXi vswitch, I ran tcpdump and see the source MAC from mTCP is still 00:00:00:00:00:00, I am wondering if this source MAC of 0 would fail on  physical switches, I will try to hardcode the source MAC in mTCP and see if it helps

**Comment by vincentmli** [comment]
I  hard coded the src MAC in mtcp/src/eth_out.c and it resolved the issue when packet needs to pass through physical swithes, so the problem is not VLAN tagging, but mTCP lack of support vmxnet3 driver in mtcp/src/dpdk_module.c or  DPDK vmxnet3 pmd lack of implementation for mac_addr_add in  vmxnet3_eth_dev_ops, this result in the src MAC address to be 00:00:00:00:00:00.

**Comment by njnumjn** [comment]
hi vincentmli:
Could you please share me your modified codes in mtcp/src/eth_out.c ?
thanks very much.

**Comment by vincentmli** [comment]
if you cloned the most recent mTCP from github, it should already have a workaround patch to resolve the MAC address being 00:00:00:00:00:00 issue, which is to use ifconfig command to manually add the MAC address to dpdk<#> interface after you bound the NIC to igb_uio. there is no special codes to mtcp/src/eth_out.c. you may also adjust 

you may just need to adjust some setting in mtcp/src/dpdk_module.c for vmxnet2 listed in https://github.com/eunyoung14/mtcp/issues/35#issue-139954994

**Comment by njnumjn** [comment]
thanks vincentmli!
after binding NIC to IGB UIO, I added MAC address (an arbitrary unused address in internal network ) to dpdk0 (a virtual dpdk driver in VMware): 
`ifconfig dpdk0 hw ether 00:50:56:8f:51:5e`
It works, Other hosts can connect to this mTCP Server now!

**Comment by eflyinghi** [comment]
I'm working with Ubuntu 14.04 on VMware Workstation 11.  I hit the same issue.  But the solution doesn't work for me. 

I tried with both "ip link set" and "ifconfig dpdk0 hw enth" to add a MAC for the dpdk0 interface, but "ip link" still showed unknown status even if the mac address was showed correctly.
6: dpdk0: mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
link/ether 00:0c:29:09:f5:3b brd ff:ff:ff:ff:ff:ff

I created a new issue before, #100 
Thanks.

**Comment by njnumjn** [comment]
@eflyinghi 
Did you run the `mtcp/dpdk-16.04/tools/setup_iface_single_process.sh` mentioned in mtcp/README ?

**Comment by eflyinghi** [comment]
@njnumjn 
Yes.  I've run the script to add the IP address and brought the interface up.  So if I run ifconfig, I could see the interface with correct both MAC and IP address.  But if I run ip link, the status of the link still showed as UNKNOWN.

**Comment by vincentmli** [comment]
have you tried to generate traffic even when the link in "UNKNOWN" state to
just see if packet get through?

**Comment by eflyinghi** [comment]
@vincentmli 
I run test epserver, I got "Checking link statusdone", no more details link status.  So it seemed that epserver cannot run with UNKNOWN state link?

So how can I run the test if packet can get through?  I'm a fresh man.

Thanks.

**Comment by vincentmli** [comment]
I am wondering if this is specific nic driver or vmware workstation
related, have you tried to use kvm as hypvervisor

**Comment by luohaha** [comment]
@vincentmli @njnumjn Hi, `ifconfig dpdk0 hw ether ` didn't work! It prints `SIOCSIFHWADDR: Operation not supported`. My Eth is vmxnet3, thanks!

**Comment by vincentmli** [comment]
try the patch in
https://github.com/eunyoung14/mtcp/issues/77#issuecomment-226876560 to see
if it works

**Comment by luohaha** [comment]
@vincentmli Thanks, already solved!
