### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [eunyoung14/mtcp#36]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/eunyoung14/mtcp/blob/c7128c5031cec5f75e2dd37fc00831c9ef3f19bb/configure.ac#L10 "Configuration checks")?

**Comment by ajamshed** [comment]
Thanks! I will update it... or you can send in a pull request.
