### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [eunyoung14/mtcp#37]
I would like to point out that identifiers like "[`__MTCP_API_H_`](https://github.com/eunyoung14/mtcp/blob/6e3920c84df19f1c84cfaf5ea30cc36b3d633cd8/mtcp/src/include/mtcp_api.h#L1)" and "[`__TCP_STREAM_H_`](https://github.com/eunyoung14/mtcp/blob/d2ad1ccfe13e38738f0d61fa640346da720e569e/mtcp/src/include/tcp_stream.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ajamshed** [comment]
You may want to send in a pull request. Thanks.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by eunyoung14** [comment]
Okay, I'll work on this.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/eunyoung14/mtcp/commit/f0fd710b8b4b8b1f82e9482e4602171f9f29714f#diff-4f3a5af3bce102c1f788c96643dd8021L1 "Renaming of include guards").
