### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [eunyoung14/mtcp#38]
The function "[gettimeofday](http://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html)" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[HandleSignal](https://github.com/eunyoung14/mtcp/blob/b5a602960700b47414a3a26ed9f1cc6581cf45b4/mtcp/src/core.c#L74)".

**Comment by ajamshed** [comment]
Thanks for the bug report elfring. I see a bunch of timer-related functions in the "Asynchronous-Signal-Safe Functions" table on the same webpage. I guess we need to replace gettimeofday() function with one of those functions. I will get to that soon.

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by ajamshed** [comment]
Thanks! I will take a look into this.

**Comment by elfring** [comment]
[The implementation of the function “HandleSignal”](https://github.com/eunyoung14/mtcp/blob/12aaaae77a2cb1c50355805c0358d05cd26e05bf/mtcp/src/core.c#L80 "Update candidate") contains details for further development considerations.
* It seems that [the function “sched_getcpu”](http://man7.org/linux/man-pages/man3/sched_getcpu.3.html "CPU determination") does not belong to the list of async-signal-safe functions.
* Array accesses can be [async-signal-unsafe](https://cwe.mitre.org/data/definitions/828.html "Signal handler with functionality that is not asynchronous-safe").
