### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [eunyoung14/mtcp#39]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_signal.html) ⇒ [FlushReadEvents](https://github.com/eunyoung14/mtcp/blob/b5a602960700b47414a3a26ed9f1cc6581cf45b4/mtcp/src/core.c#L379)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html) ⇒ [InitLogThreadContext](https://github.com/eunyoung14/mtcp/blob/d887ff401a83cc93d341d75d2e0f28066eda0962/mtcp/src/logger.c#L76)

**Comment by ajamshed** [comment]
Sure. I have added these requests in my TODOs list. I will address these issues in my next mTCP update.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

**Comment by ajamshed** [comment]
Thanks. I will try to run some analysis tool on mTCP in the coming weeks.

**Comment by elfring** [comment]
There are [still update candidates left over](https://github.com/eunyoung14/mtcp/blob/9ea3248722405fcf9a061719b10902675cbd409e/mtcp/src/logger.c#L76 "Update candidate: InitLogThreadContext()"), aren't there?
