### ISSUE TITLE
Amazon EC2 support

### ISSUE THREAD

**Issue by simonhf** [eunyoung14/mtcp#4]
Is there any way to get mTCP working with Amazon EC2 virtual NICs?

**Comment by ajamshed** [comment]
Simon,
mTCP provides support for Intel DPDK drivers (that offers Xen hypervisor extensions). We do plan to extend mTCP in sandboxed environments in the future. However we are currently short in manpower. If you are interested in enabling virtualised mTCP support asap, I suggest that you go through io_module.c and dpdk_module.c files as references. We will notify you once Xen-enabled mTCP is ready.
