### ISSUE TITLE
dpdk0 does not appear

### ISSUE THREAD

**Issue by ATCP** [eunyoung14/mtcp#41]
Hi, mtcp team,

sorry for the interruption
 
after installing your mtcp modified DPDK and using igb_uio driver in our device, there is no new logical interface dpdk0 created, so I cannot set a IP mask for it in the next step using your set_iface_single_process.sh, Am I missing some step? my machine is running centos 6.5 with Linux kernel 3.10.25, and NIC using dpdk driver is Intel 82580 Gigabit NIC

Thanks

**Comment by ajamshed** [comment]
Please check whether your NIC supports dpdk I/O: http://dpdk.org/doc/nics.
It looks like it does not.

To be double-check, please insert igb_uio module from the unmodified dpdk-2.2.0 toolkit and 
see if you can run sample dpdk applications.

**Comment by ajamshed** [comment]
Oops. I just realised that your NIC should support dpdk (igb). I still suggest that you check whether the sample dpdk applications work and then see that you have followed all the steps carefully. Let me know if you are still stuck.

**Comment by ATCP** [comment]
I tried intel 82580 with the original dpdk-2.2.0 and found ti it works for dpdk test and testpmd application, but it does not work for the modified one as shown in my previous post. additionally, it cannot be unbind using the tools/dpdk_nic_bind.py, but can be unbind/bind using original dpdk tools. 

Then I tried the 10Gbps NIC  intel 82599EB 10G SFI/SFP+ network connection, it works for mtcp, so I think Intel 82580 might not work for mtcp dpdk

**Comment by ajamshed** [comment]
Oops... looks like I messed up the igb_uio driver patch... let me get hold of an Intel 1G card and test it out. I will get back to you on this soon.

**Comment by ajamshed** [comment]
Can you please check if mTCP works for 82580? I tested the new patch with Intel I350 and it is now working fine (can't find Intel 82580 NIC in my lab). Thanks for reporting the problem.

**Comment by ATCP** [comment]
yes it works, Thanks a lot
but it works for core number N<=8, not for N>8, do you know why, maybe not relevant to the code
it reports the error like
"Initializing port 0... EAL: Error - exiting with code: 1
  Cause: Cannot configure device: err=-22, port=0
"

**Comment by ajamshed** [comment]
Intel 82580 chipset can only support up to 8 H/W queues.
http://www.intel.com/content/www/us/en/embedded/products/networking/82580-eb-db-gbe-controller-datasheet.html

**Comment by ATCP** [comment]
I see Thanks
