### ISSUE TITLE
Does not compile in FreeBSD-9.3(netmap version)

### ISSUE THREAD

**Issue by millken** [eunyoung14/mtcp#42]
```
[root@FreeBSD-9 /github/mtcp/mtcp/src]# make
"Makefile", line 33: Missing dependency operator
"Makefile", line 35: Need an operator
"Makefile", line 37: Need an operator
"Makefile", line 39: Missing dependency operator
"Makefile", line 41: Need an operator
"Makefile", line 43: Need an operator
"Makefile", line 53: Missing dependency operator
"Makefile", line 56: Need an operator
"Makefile", line 58: Need an operator
"Makefile", line 60: Missing dependency operator
"Makefile", line 61: Need an operator
"Makefile", line 63: Need an operator
"Makefile", line 87: Missing dependency operator
```

**Comment by ajamshed** [comment]
We haven't really tested mTCP on FreeBSD. With some slight updates to the stack, I think you will be able to get mTCP working. The current error has to do with Makefile interpretation though. Please try using 'gmake' instead.

**Comment by njnumjn** [comment]
@millken : I think you should run `dos2unix Makefile` first

**Comment by ajamshed** [comment]
njnumjn,

We have not officially ported mTCP stack to FreeBSD yet. You can try using `gmake` to get rid of this error. 

But I think you'll have to do slightly more manual work to fully port the stack. For a start, I suggest that you use the mTCP-netmap version. You'll also need to remove the libnuma dependency from the mTCP stack and replace it with the appropriate FreeBSD function. Also, you will have to change the header files (linux/ip.h, linux/tcp.h,...) to the netinet/ version. I was able to get an experimental version of mTCP in FreeBSD working. But I need to test it more extensively before I can release it on github. I suggest that you try the porting on your own and let me know if you have any further questions.
