### ISSUE TITLE
Streams may stall if the receive buffer is >64K

### ISSUE THREAD

**Issue by betasheet** [eunyoung14/mtcp#43]
In the process of debugging, I discovered a bug in MTCP where the receiving side of a stream may "stall" if the rcvbuffer is configured to be larger than 65KB.

In tcp_out.c, there's a line that updates the rvc-window:
`tcph->window = htons(MIN((uint16_t)window32, TCP_MAX_WINDOW));`

It casts the window32 to a uint16 before comparing to the maximum value, thus if window32 is e.g. 128K, it'll be cast down to a uint16 of value 0. The cast needs to be moved outside the MIN comparison:
`tcph->window = htons((uint16_t)MIN(window32, TCP_MAX_WINDOW));`

Cheers,
Eric

**Comment by eunyoung14** [comment]
Hi Eric,

You're right. The cast should be done after the MIN comparison.
Thank you for reporting this. I'll make changes to the repository.
