### ISSUE TITLE
the diff between mTCP DPDK and upstream DPDK

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#47]
Hi,

I am trying to compile mTCP with the most recent upstream DPDK git release dpdk v2.2.0-rc4, I patched up lib/librte_eal/linuxapp/igb_uio/igb_uio.c diff from mTCP DPDK and also copied igb_uio/igb_uio.h, v2.20-rc4 dpdk compiles file with the mTCP DPDK changes, I can also see dpdk0 interface created after binding the interface, but I failed to compile mTCP code with the v2.2.0-rc4, typical error below:

In file included from /home/admin/mtcp/dpdk/include/rte_ether.h:50:0,
                 from /home/admin/mtcp/dpdk/include/rte_ethdev.h:185,
                 from io_module.c:17:
/home/admin/mtcp/dpdk/include/rte_memcpy.h: In function ‘rte_memcpy’:
/home/admin/mtcp/dpdk/include/rte_memcpy.h:870:2: warning: implicit declaration of function ‘_mm_alignr_epi8’ [-Wimplicit-function-declaration]
  MOVEUNALIGNED_LEFT47(dst, src, n, srcofs);
  ^
/home/admin/mtcp/dpdk/include/rte_memcpy.h:870:2: error: incompatible type for argument 2 of ‘_mm_storeu_si128’
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/include/xmmintrin.h:1246:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.8/include/x86intrin.h:34,
                 from /home/admin/mtcp/dpdk/include/rte_vect.h:67,
                 from /home/admin/mtcp/dpdk/include/rte_memcpy.h:46,
                 from /home/admin/mtcp/dpdk/include/rte_ether.h:50,
                 from /home/admin/mtcp/dpdk/include/rte_ethdev.h:185,
                 from io_module.c:17:

I imagine there could be some other diffs I am missing from mTCP DPDK.

could you release the complete diff patches between mTCP DPDK and upstream DPDK ? I would like to experiment some new DPDK features with mTCP.

Thanks!

Vincent

**Comment by vincentmli** [comment]
it looks like the mTCP github repo contained DPDK build directory and binaries, it make it a little bit difficult to track the mTCP DPDK changes and upstream DPDK

**Comment by ajamshed** [comment]
Sorry Vincent, you were almost there with the patch. You just need to add one more line in mk/rte.cpuflags.mk file (at the end of file):

$(shell echo ${MACHINE_CFLAGS} > ${RTE_SDK}/${RTE_TARGET}/include/cflags.txt)

Recompile dpdk-2.2 toolkit and that should do it.

**Comment by vincentmli** [comment]
Thanks Asim, that solves the problem

**Comment by ajamshed** [comment]
Hi Vincent, I left some comments regarding your pull requests. Did you find time to look at them?

**Comment by yilongli** [comment]
I ran into this problem today when I was trying to build mTCP with Mellanox DPDK. I solved the problem myself before seeing this thread. Could you please update the documentation to make this problem clear? Basically, people need to copy ```mtcp/dpdk-X.X/mk/rte.lib.mk``` and ```mtcp/dpdk-X.X/mk/rte.cpuflags``` into their ```dpdk/mk/``` directory.

**Comment by ajamshed** [comment]
Hi yilongli,

Sorry to be responding to you this late. This issue is briefly mentioned in the README file. We normally advise the mTCP users to use our version of dpdk because we have patched ``igb_uio`` kernel module driver (for Intel-based Ethernet adapters). Since you are using Mellanox cards, you can use any version of dpdk in practice. I will mention about the changes made in ``rte.app.mk`` and ``rte_cpuflags.mk`` files in the README as well. Thanks!
