### ISSUE TITLE
netmap support

### ISSUE THREAD

**Issue by simonhf** [eunyoung14/mtcp#5]
Why not support netmap [1] ? This would allow mTCP to work with a larger number of commodity so-called 'dedicated' rental servers which use a single NIC. Why? Because netmap allows certain NIC packets (e.g. ssh) to be filtered towards to the regular kernel network stack, while allowing user land to snaffle the rest.

[1] http://info.iet.unipi.it/~luigi/netmap/

**Comment by ajamshed** [comment]
Simon,
That's a good idea. We often get asked whether mTCP can be extended to provide netmap and libpcap (for detailed performance debugging analysis) support. We have these tasks listed up in the TODOs file. We will get back to you once these modules are done.

**Comment by simonhf** [comment]
Thanks, that's music to my ears! Please let me know when netmap support is ready and I'll be happy to test it out for you.

**Comment by simonhf** [comment]
FYI I managed to get netmap working on a VMware guest running Ubuntu... which might be a convenient way for many people to try out mTCP without having to have a separate box?

**Comment by ajamshed** [comment]
That's great. I will let you know once we release the stable version of mTCP-netmap.

**Comment by simonhf** [comment]
Sounds good. Any idea for a very rough ETA for that? days / months / years? :-)

**Comment by ajamshed** [comment]
Hi Simon,
One of our fellow graduate students is currently implementing the netmap plugin for mTCP. I am guessing that he will be done with it this month.

**Comment by simonhf** [comment]
Sounds very good.

**Comment by simonhf** [comment]
Any update regarding the netmap plugin? :-)

**Comment by ajamshed** [comment]
Hi Simon,

I am sorry but we have not been able to get the netmap plugin ready yet. The person who initially volunteered for the job was reassigned some other work. The netmap porting task is still on hold. Actually we are actively looking for volunteers who could help us complete the netmap task. The moment we have the port ready, we will notify you.

**Comment by ajamshed** [comment]
The netmap module is finally ready.
