### ISSUE TITLE
bind multiple NICs with mtcp?

### ISSUE THREAD

**Issue by congnguyenthe** [eunyoung14/mtcp#50]
Hello mtcp developers,

I would like to run mtcp on multiple NICs using different core each NIC card, is this possible or not?
For example:
NIC 82:00.0 using core 0,1,2,3,4
NIC 82:00.1 using core 5,6,7,8
NIC 85:00.1 using 9,10,11,12

Thanks

**Comment by ajamshed** [comment]
I am not sure whether this configuration (core<-->NIC queue bindings) may work for single-process model unless the config.c and io_module.c files are updated. However I think this may work if you run the multi-process version of mtcp-dpdk. For example:

NIC 82:00.0 
    [Core 0] master, [Cores 1~4] slaves
NIC 82:00.1
    [Core 5] master, [Cores 6~8] slaves
NIC 85:00.1
    [Core 9] master, [Cores 10~12] slaves

By the way, I am assuming that you are using a 12-core machine?? (Just wondering whether you actually meant Cores 0~11). I would recommend that you go through epserver.c example to see how a multi-process version for mTCP might work. I apologize for my minimal documentation in advance!

**Comment by congnguyenthe** [comment]
Many thanks for your reply, in fact, my server has 24 cores (without hyper threading) and NIC support up to 64 queues. I consider this use case because in some cases, using this core is more effective than that core (like cores on same NUMA with NIC) and each core is working on one NIC only. Anw, I will try your suggestion. 
Best regards,

**Comment by ajamshed** [comment]
I just realized that mTCP stack implicitly assumes that queue-id == core-id (which does not apply in your setup). So you may have to carefully set NIC queue <---> core-id bindings.This may require small changes to the source code. Out of curiosity... which NIC are you using that can possibly support up to 64 RSS queues?

**Comment by congnguyenthe** [comment]
Thanks for your information. I will take it carefully. About the NIC card, I forgot its name, but it's 40Gb/s NIC.
