### ISSUE TITLE
reduce in-host delay

### ISSUE THREAD

**Issue by ATCP** [eunyoung14/mtcp#53]
Hi, mtcp team, 

now I can initialize over 1.6 Million tcp connection with epwget, connecting epserver, each tcp connection sends a request of 200 bytes from epwget every 60 s, and epserver sends back an response packet, e.g., 200 bytes, to epwget. from the wireshark, I observe the in-host processing delay, i.e., the delay between the time the request arriving at the epserver host and the response sent out of the epserver host, can over 500ms, the same observation can be found for the epwget host, thus the response time of the request can be seconds. 

so does any tuning I can apply to reduce this in-host processing delay so that the in-host processing delay can be further reduced for this particular scenario

Thanks
Ke

**Comment by vincentmli** [comment]
I saw the same delay when there were millions of connection going on, I am wondering if this is the design of mTCP like sending packets in batch mode? store control SYN, ACK, packets in each control packet list? mTCP is uniq design compare to Linux or BSD TCP stack. just my 2 cents. I am curious to know the answer too.

**Comment by eunyoung14** [comment]
We extensively used batching to maximize the packet I/O throughput, but it seems it's making delay in your large concurrency settings.
Please see the function `AddtoControlList()` in tcp_out.c and try turning on the `TRY_SEND_BEFORE_QUEUE` flag. This will make the control packets not to be queued to the control packet list and sent directly.
However, we've not tested this option for a long time, so it may have unknown side effects...
