### ISSUE TITLE
mTCP initial sequence number lack of randomness

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#54]
in mtcp/src/tcp_stream.c, next_seed is set to 1 

```
/* for rand_r() functions */
static __thread unsigned int next_seed = 1;

and
        stream->sndvar->iss = rand_r(&next_seed) % TCP_MAX_SEQ;
```

rand_r man page says:
"
 Like rand(), rand_r() returns a pseudo-random integer in the range [0, RAND_MAX].  The seedp argument is a pointer to an unsigned int that is used to store state  between  calls.
       If  rand_r()  is  called  with the same initial value for the integer pointed to by seedp, and that value is not modified between calls, then the same pseudo-random sequence will result.
"

so when I run command below repeatedly from bash prompt, the SYN packet sequence number is always same:
# ./apps/example/epwget 10.1.72.17 1

this could result in poor interaction with servers tcp stack, if I modified the next_seed to be time based, 

```
+       next_seed = time(NULL);
```

it improves the randomness, is there better way to improve the randomness of tcp ISS?

**Comment by ajamshed** [comment]
I think this is a good idea. next_seed variable should be initialized with a timestamp as you have suggested. mTCP stack should be patched.

**Comment by vincentmli** [comment]
Hi Asim

I created pull request for this issue, could you please merge it? Thanks!

Vincent

**Comment by ajamshed** [comment]
Hi Vincent,

I looked at the pull request. I think it will be better if the next_seed is initialized only once by `time(NULL)` after which rand_r(&next_seed) can be used to set iss. This will be more efficient in the long term.

**Comment by vincentmli** [comment]
you mean initialize next_seed like below ?

```
/* for rand_r() functions */
static __thread unsigned int next_seed = time(NULL);
```

I got compile error if I do that.

tcp_stream.c:41:1: error: initializer element is not constant
 static __thread unsigned int next_seed = time(NULL);
 ^

**Comment by ajamshed** [comment]
Apologies for the delayed response. The assignment needs to take place during mTCP initialization, e.g. core.c:InitializeMTCPManager().

**Comment by vincentmli** [comment]
you mean add a next_seed member in mtcp_manager struct and initilize it
with something like mtcp_>next_seed = time(NULL) in InitializeMTCPManager,
just want to be clear :)

**Comment by ajamshed** [comment]
I went through the code a bit deeply... and I think the best way will be to introduce a couple of functions.

```
/* this will include the next seed initialisation and flow_pool creation (tcp_stream.c) */
InitializeTCPStreamManager(...);

/* here we will destroy flow_pool */
DestroyTCPStreamManager(...); 
```

`tcp_stream.h` will have the function declarations.
Let's keep `next_seed` as `static __thread unsigned int` for now.

**Comment by vincentmli** [comment]
cool, glad you will have more complete optimal solutions for this.

**Comment by ajamshed** [comment]
Hi Vincent,
I added an `InitializeTCPStreamManager()` function that updates the per-thread `next_seed` value. I will expand this function in my future commits. Thanks for pointing out this issue.
