### ISSUE TITLE
mtcp_connect hangs after bind with INADDR_ANY

### ISSUE THREAD

**Issue by mishka99** [eunyoung14/mtcp#58]
Hi.
I stumbled upon an issue where a test application (incorrectly or on purpose) did a bind with addr and port of zeroes (same as INADDR_ANY) and then issued connect which causes MTCP to create a stream with source address/port of zeroes - so there is never return traffic.

I changed mtcp_connect() to check for bind flag set and source addr of zeroes in which case it goes to the 'else' case where it does source address lookup and port randomization.

Please let me know if that makes sense as a fix for the described condition.
thanks
Michael

**Comment by ajamshed** [comment]
Hi,

Your proposed solution makes sense. But please make sure that you call mtcp_init_rss() function before you call mtcp_connect(). I will fix this issue the next time I update the code.

**Comment by mishka99** [comment]
Hi,
Yes, I for sure call mtcp_init_rss() before mtcp_connect() as I've followed your examples.
Thank you!

**Comment by arunkumarsit** [comment]
Hi,
I faced similar issue. The value of zero for port number is passed during mtcp_bind() in server side. And mtcp_listen() also successful for the same.
After finding this I used to generate the port number using port randomization and my application is working as expected.
So in my opinion, the fix should be in mtcp_bind() API.

In case of Kernel, the bind() system call will assign some random value to the port number when the passed port number is zero.
This is what happening in NFS service for mountd and nlockmgr services.
Whether mtcp_bind() API can be supported in the same way as kernel bind() functionality? (assigning random port values when the passed value is zero).

Let me know your views. Please correct me if I am wrong.

**Comment by ajamshed** [comment]
I have fixed this issue in my latest commit.

**Comment by mishka99** [comment]
Quick question - if addr is INADDR_ANY but port is NOT INPORT_ANY, then in the 'else' case you should probably preserve the requested port instead of overwriting it - the easiest way to do it is to save it before calling FetchAddress() and then replace it back into socket->saddr.

**Comment by mishka99** [comment]
You also made a typo - switched the compare values (even though both are zeroes, the names should match the fields):

            socket->saddr.sin_port != INADDR_ANY &&
            socket->saddr.sin_addr.s_addr != INPORT_ANY) {
should be
            socket->saddr.sin_port != INPORT_ANY &&
            socket->saddr.sin_addr.s_addr != INADDR_ANY) {

**Comment by ajamshed** [comment]
Thanks for pointing out the mistake. I think the latest fix should now resolve this issue.
