### ISSUE TITLE
blocking support

### ISSUE THREAD

**Issue by mishka99** [eunyoung14/mtcp#59]
Hi,
I notice that MTCP requires use of non-blocking sockets with mtcp_epoll_wait.  What happens if I don't turn on non-blocking and then issue mtcp_epoll_wait?  Is there additional delay?  Any other side effects?

There is a comment around define of BLOCKING_SUPPORT that states that it's now obsolete - please explain why is it obsolete?

I tried enabling BLOCKING_SUPPORT but several files won't compile as it looks like that functionality hasn't been used/tested in quite a while and it references struct fields that are either gone or moved elsewhere.

I can attempt to fix the compilation issues but it would be better if you guys can do it since you already know which fields were moved or deleted and why.

thanks
Michael

**Comment by mishka99** [comment]
Ok, it was easy enough to fix the minor compilation issues.  I also had to turn off USE_SPIN_LOCK since pthread cond var calls require mutex.  But running it without setting nonblock and calling epoll doesn't work, it just hangs in connect.  Any ideas/suggestions?
thanks
Michael

**Comment by ajamshed** [comment]
I haven't tested BLOCKING_SUPPORT in a very long time. I think blocking socket I/O support was dropped some time ago . I will see if we can get it working.

**Comment by mishka99** [comment]
Appreciate anything you can help with.  It's a bit of a hassle to adapt existing apps to MTCP model since it lacks blocking.
thanks

**Comment by theanoli** [comment]
I'd like to follow up on this as I'm also trying to port an application that uses blocking reads--has blocking support been added yet?

Also, do you know why blocking support was dropped (e.g., some technical challenge, not enough demand)? I might be able to help with (re-)implementation, depending on the problem.

Thanks, 
Theano.

**Comment by ajamshed** [comment]
Support for blocking mode was disabled long before I joined the team. I don't really remember why it was deprecated in the first place. I will like to involve @eunyoung14 in this conversation. Maybe he will have  a better idea about this.

**Comment by eunyoung14** [comment]
At first we supported blocking calls to test the correctness of TCP implementation, but latter we moved on to nonblocking calls with event system. We recommend using a application thread per an mtcp thread for performance, which can never be achieved by the blocking model. The blocking support is depreciated just because we didn't need it any more and thus not managed for a long time. You may be able to revive it as some of the code still exists.

**Comment by theanoli** [comment]
Got it, thank you.
