### ISSUE TITLE
MTCP API documentation!

### ISSUE THREAD

**Issue by loveqingping** [eunyoung14/mtcp#60]
I need the MTCP API documentation, and who will provide it?

**Comment by ajamshed** [comment]
We will be releasing man pages for mTCP functions soon. I suggest that you see our mTCP paper in the meantime: http://www.ndsl.kaist.edu/~kyoungsoo/papers/mtcp.pdf

FYI (mTCP man pages -- beta version): http://wine2.kaist.ac.kr/

**Comment by loveqingping** [comment]
Thanks!
