### ISSUE TITLE
missing dpdk0 network interface

### ISSUE THREAD

**Issue by mishka99** [eunyoung14/mtcp#62]
This might be a simple/dumb question... I don't see dpdk0 (or any dpdk?) network device after insertion of the igb_uio.ko module - even though it prints that it's registering it.

My kernel: 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

dmesg output (with added info)
[204102.079109] igb_uio 0000:07:00.0: uio device 12 (dpdk0) registered with irq 4c

ifconfig/ip link don't show dpdk0 interface - getifaddrs() doesn't have it in the list either

I've used the normal interface name (example eth4) in MTCP conf file (instead of dpdk0) and it seems to work just fine - but wanted to understand why I can't see dpdk0

Somewhere in the docs it says that igb_uio was modified to register as a network device to provide ability for standard tools (ethtool, ip, etc) to retrieve network stats from MTCP internals - did I read that right?

**Comment by ajamshed** [comment]
Yes. The igb_uio.c file was updated for this purpose. Please see if your OS is renaming the dpdk0 interface name. Some distributions such as Fedora tend to use some scripts (using ifrename etc.) to change the names of interfaces in the background. You can probably search for dmesg log to see if your iface has been renamed.

**Comment by mishka99** [comment]
Hi.  Yes, I thought of that too, but I don't see anything being renamed.  Even if renamed, whatever that new name would have been, the interface should have been added to the in-kernel network device table and getifaddr() should have returned it in the list - but it doesn't (so that loop name matching doesn't find dpdk0 if it is specified in the conf file).  Anyway, I'll do more debugging in that area later.

**Comment by mishka99** [comment]
One more data point, I'm using CentOS 7.1
