### ISSUE TITLE
value truncated after assignment

### ISSUE THREAD

**Issue by mohsinkazmi** [eunyoung14/mtcp#63]
In struct netmap_private_context, rcv_pkt_len[index] is uint8_t which can hold max value of 0x100. while the assignment is from uint16_t len in struct netmap_slot. So after assignment, value of the original message length truncated  upto 256Bytes if it is greater than 256 Bytes.

**Comment by ajamshed** [comment]
Thanks for pointing it out. I haven't tested the netmap module in detail yet. Please let me know if you find more issues. I do plan to work on this module in the future.

**Comment by mohsinkazmi** [comment]
Thanks Jamshed.

commit f961e42e158442b09acd9cc7f549ba07deec5d6a resolves the issue.
