### ISSUE TITLE
turn off compilation of PS code

### ISSUE THREAD

**Issue by mishka99** [eunyoung14/mtcp#64]
Low priority but would be nice if DISABLE_PSIO actually disabled compilation of all of PSIO code and data structures (and don't provide a -I../../io_engine/include in generated Makefile).  While at it, double check that it's also true when DISABLE_NETMAP and DISABLE_DPDK are defined.

**Comment by ajamshed** [comment]
This is partly patched up. I will see if the code can be cleaned up more a bit later..
