### ISSUE TITLE
MTCP over a VF device

### ISSUE THREAD

**Issue by mishka99** [eunyoung14/mtcp#65]
Have you guys tried running MTCP/DPDK over a VF device (using 82599 and ixgbe)?  I'm having problems getting it going as it sees zeroes in the MACs and if I specify static macs in the conf file, then it never goes past the SYN stage.

**Comment by vincentmli** [comment]
I have a code hack patch to resolve the all zeros MAC address issue see https://github.com/eunyoung14/mtcp/issues/51#issuecomment-207559616

**Comment by mishka99** [comment]
Thanks for the suggestion - I'll try it, hope it works.  I am using Intel 82599 which is the ixgbe driver so it should have copied the MAC properly - however, I'm thinking that in case of VF device, it's copying from the wrong field, or that field isn't being populated properly by other parts of ixgbe driver (now I'm wondering if ixgbevf is different device type from ixgbe and fails that switch check) - I'm still checking into that.

**Comment by mishka99** [comment]
So the proposed solution (in #51) doesn't work for me as in my configuration I can't generate dpdk0 network device (it's not showing up in getifaddrs() output) and I don't want to hard code the nic name I'm using (though I guess I can get that from the CONFIG.eths[i].dev_name).

I verified that igb_uio module doesn't recognize the Intel VF devices - hence fails to retrieve proper mac.  When adding static ARP entry into arp.conf file, it fills the mac ok but connect hangs - never makes it past initial SYN stage.

I'm not sure what other side effects exist when adapter type isn't IXGBE or IGB?

**Comment by mishka99** [comment]
Here is more data for you guys - maybe it will help.

I tried a quick hack in igb_uio.c to recognize Intel 82599 VF device but it requires a more in-depth work to map proper register sets and make sure register access are correct.

Note, I'm using the VF device itself in the MTCP .conf file (since I don't see dpdk0, etc).  When SetInterfaceInfo() does the getifaddrs() it finds the VF device (since it is up and has an IP assigned) - but it's MAC is zeroes.   The rte_eth_macaddr_get() returns the correct MAC so when I detect MAC of zeroes after getifaddrs() loop, I override it with MAC from rte_eth_macaddr_get() - hard coded for one device for now.  That solves the source MAC address problem.

If my config/arp.conf table is empty, MTCP tries to send an ARP request to discover destination MAC.  I get ARP request timeouts and I don't see anything going on the wire so it never makes it past the VF device.  If I add a static MAC entry into config/arp.conf then it fills the src/dst MACs correctly but then gets stuck in infinite send SYN loop as that traffic also never makes it past the VF device.  So something else in the MTCP/DPDK interaction isn't happy about use of the VF device.

Interesting side note.  When VF device is still owned by ixgbe/ixgbevf, it shows a correctly assigned MAC (getting that to work was a whole other little nightmare).  When using DPDK's setup.sh to bind the VF device to DPDK (to igb_uio), the MAC gets reset to zeroes and there is no direct (cmdline) way to change it.  I haven't looked deep into DPDK APIs to see if there is a programmatic method of changing MAC of the bound device (VF or PF).

Also, there is no way to unbind VF from igb_uio AND re-bind to ixgbe/ixgbevf due to the method employed in the script since VF devices show up somewhat differently in the /sys tree.  After option 29 in DPDK setup.sh, that VF device shows up as "other" (orphaned).  The only way to get it back to be bound with ixgbe/ixgbevf is to rmmod igb_uio.ko module - after rmmod, the VF device auto-magically gets bound back to ixgbe/ixgbevf.

Maybe all that helps somehow to resolve some issues.

**Comment by wtao0221** [comment]
Hi,

Do you figure out how to use mTCP with VF correctly ?

**Comment by ajamshed** [comment]
@wtao0221,

Support for VFs is currently not available. We will let you know once this feature has been activated.
