### ISSUE TITLE
latest official DPDK

### ISSUE THREAD

**Issue by mishka99** [eunyoung14/mtcp#66]
Have you considered syncing to the latest official DPDK release?  If the APIs MTCP uses are still the same and if the only changes are to the igb_uio driver, then it should be a straightforward merge? (famous last words:)

**Comment by mishka99** [comment]
If I find time, I'm seriously considering trying MTCP with latest DPDK release.  Besides hacking igb_uio.c, any other gotchas that I may need to lookout for?

**Comment by vincentmli** [comment]
I have done that see https://github.com/eunyoung14/mtcp/issues/47, 
the gotchas you need to lookout for, see
https://github.com/eunyoung14/mtcp/issues/47#issuecomment-204993282

**Comment by mishka99** [comment]
Thank you Vincent, I'll take a look.

**Comment by ajamshed** [comment]
I have now updated mTCP to support dpdk-16.04
