### ISSUE TITLE
Kernel panic when binding interface to igb_uio

### ISSUE THREAD

**Issue by marqs85** [eunyoung14/mtcp#68]
After several bind/unbind cycles via dpdk_nic_bind.py, binding seems to cause a kernel panic at netdev_stats(). The crash has occurred on kernels 3.11.2 and 4.4.0. I traced this back to "cards_found" (igb_uio.c), which seems to be incremented during each bind but never reset. Eventually it gets increased beyond MAX_DEVICES, resulting to an out-of-array read in netdev_stats.

**Comment by ajamshed** [comment]
Thanks for catching the bug. I have updated the code. I hope this works fine now.
