### ISSUE TITLE
Can I use mtcp for routing packets?

### ISSUE THREAD

**Issue by alexsalig** [eunyoung14/mtcp#74]
> Yes, mTCP allows static route and arp configuration.

So why in `SendTCPPacketStandalone` function calls you always set `payload` to `NULL`?

**Comment by eunyoung14** [comment]
mTCP is a TCP stack for end hosts and does not support routing general IP packets. That statement means we support static routing for the end hosts.
By the way, we used `SendTCPPacketStandalone` function for only the `RST` packets which does not have any payload. If you want to implement other features using the function, you can set the non-null payload value.
