### ISSUE TITLE
Set the mailing list archive to public

### ISSUE THREAD

**Issue by iwanbk** [eunyoung14/mtcp#76]
Hi,

I found this mailing list page http://mail.ndsl.kaist.edu/mailman/listinfo/mtcp and see that the archive page is private.

I think it will be much better if:

- it set to public. So it can be indexed by google.
- add http://mail.ndsl.kaist.edu/mailman/listinfo/mtcp to readme, so people can easily subscribe to it.

**Comment by ajamshed** [comment]
Thanks for the suggestion. We will try to put up a mailing list soon.

**Comment by ajamshed** [comment]
Hi iwanbk,

We have updated the mailing list address and made the archive public. Unfortunately we could not release the archive of the previous mailing list due to privacy reasons. However all emails exchanged in the new mailing list (mtcp-user) will be public from now on.
