### ISSUE TITLE
mTCP ixgbevf support 

### ISSUE THREAD

**Issue by vincentmli** [eunyoung14/mtcp#77]
### 1,  retrieve_dev_specs in  lib/librte_eal/linuxapp/igb_uio/igb_uio.h

it is  trivial to add IXGBE VF vendor id and device id so retrieve_dev_specs can return a dev_type IXGBEVF.
### 2 igbuio_pci_probe(struct pci_dev *dev, const struct pci_device_id *id) in lib/librte_eal/linuxapp/igb_uio/igb_uio.c

```
501         adapter->type = retrieve_dev_specs(id);
502         /* recover device-specific mac address */
503         switch (adapter->type) {
504         case IXGBE:
505                 hw_i = &adapter->hw._ixgbe_hw;
506                 hw_i->back = adapter;
507                 hw_i->hw_addr = ioremap(pci_resource_start(dev, 0),
508                                        pci_resource_len(dev, 0));
509                 if (!hw_i->hw_addr) {
510                         err = -EIO;
511                         goto fail_ioremap;
512                 }
513                 break;
514         case IGB:
515                 hw_e = &adapter->hw._e1000_hw;
516                 hw_e->back = adapter;
517                 hw_e->hw_addr = ioremap(pci_resource_start(dev, 0),
518                                       pci_resource_len(dev, 0));
519                 if (!hw_e->hw_addr) {
520                         err = -EIO;
521                         goto fail_ioremap;
522                 }
523                 break;
524         }
```

question: 
**do I need to add similar IXGBEVF switch case like IXGBE ?** 
**does the ioremap apply to IXGBEVF ?**
### 3 retrieve_dev_addr(struct net_device *netdev, struct net_adapter *adapter)

```
423         switch (adapter->type) {
424         case IXGBE:
425                 hw_i = &adapter->hw._ixgbe_hw;
426                 rar_high = IXGBE_READ_REG(hw_i, IXGBE_RAH(0));
427                 rar_low = IXGBE_READ_REG(hw_i, IXGBE_RAL(0));
428
429                 for (i = 0; i < 4; i++)
430                         netdev->dev_addr[i] = (u8)(rar_low >> (i*8));
431
432                 for (i = 0; i < 2; i++)
433                         netdev->dev_addr[i+4] = (u8)(rar_high >> (i*8));
434                 break;
435         case IGB:
436                 hw_e = &adapter->hw._e1000_hw;
437                 rar_high = E1000_READ_REG(hw_e, E1000_RAH(0));
438                 rar_low = E1000_READ_REG(hw_e, E1000_RAL(0));
439
440                 for (i = 0; i < E1000_RAL_MAC_ADDR_LEN; i++)
441                         netdev->dev_addr[i] = (u8)(rar_low >> (i*8));
442
443                 for (i = 0; i < E1000_RAH_MAC_ADDR_LEN; i++)
444                         netdev->dev_addr[i+4] = (u8)(rar_high >> (i*8));
445                 break;
446         }
```

question:

**do I need to add switch case for IXGBEVF ?**
*_can the IXGBE_READ_REG register read apply to IXGBEVF ? *_
### 4 s32 ixgbe_get_mac_addr_vf(struct ixgbe_hw *hw, u8 *mac_addr) in drivers/net/ixgbe/base/ixgbe_vf.c

```
476 s32 ixgbe_get_mac_addr_vf(struct ixgbe_hw *hw, u8 *mac_addr)
477 {
478         int i;
479
480         for (i = 0; i < IXGBE_ETH_LENGTH_OF_ADDRESS; i++)
481                 mac_addr[i] = hw->mac.perm_addr[i];
482
483         return IXGBE_SUCCESS;
484 }
```

question:

**when IXGBE VF port is bound to igb_uio driver (dpdk<#> created), is the hw->mac.perm_addr[]  populated at same time? if so I could copy hw->mac.perm_addr[] to netdev-dev_addr[]. but I think hw->mac.perm_addr[] is populated when IXGBE VF PMD driver is initialized and loaded when  mTCP app start running, any idea?**

**Comment by vincentmli** [comment]
I did an indirect workaround by implementing a ndo_set_mac_address to allow me to use ifconfig command to add the MAC address manually after binding the port to igb_uio driver. for example:

# ifconfig dpdk0 hw ether 52:54:00:EA:6E:3E

```
/**
 * netdev_set_mac - Change the Ethernet Address of the DPDK NIC
 * @netdev: network interface device structure
 * @p: pointer to an address structure
 *
 * Returns 0 on success, negative on failure
 **/
static int netdev_set_mac(struct net_device *netdev, void *p)
{
        struct sockaddr *addr = p;
        if (!is_valid_ether_addr((unsigned char *)(addr->sa_data)))
                return -EADDRNOTAVAIL;
        memcpy(netdev->dev_addr, addr->sa_data, netdev->addr_len);
        return 0;
}
/*----------------------------------------------------------------------------*/
/**
 * A naive net_device_ops struct to get the interface visible to the OS
 */
static const struct net_device_ops netdev_ops = {
        .ndo_open               = netdev_open,
        .ndo_stop               = netdev_open,
        .ndo_start_xmit         = netdev_xmit,
        .ndo_set_rx_mode        = netdev_no_ret,
        .ndo_validate_addr      = netdev_open,
        .ndo_set_mac_address    = netdev_set_mac,
```

**Comment by ajamshed** [comment]
Vincent, sorry I still haven't looked at extending mTCP to virtualized environments. It looks like you kind of figured out how the igb_uio patch works for mTCP. ioremap/iounmap are being used to read the MAC address of the interface from the registers. 

I really need to find time to update mTCP with virtualization support. My plan is to release the patch for netmap vale and ixgbe-vf together..... soon :) :8ball:

**Comment by vincentmli** [comment]
no problem, I thought it would be nice to run mTCP in Amazon AWS "enhanced networking" instance that support SR-IOV and has ixgbe-vf

**Comment by ajamshed** [comment]
If you have successfully updated the code, can you please forward me the patch (pull request.. with detailed README-type instructions) on how to set the environment? Thanks!

**Comment by vincentmli** [comment]
I only did an initial trial on AWS with mTCP with multiple network
interfaces, my plan is to use one network interface for management with
elastic public ip, second interface with elastic public ip for mTCP, but
AWS has some hidden rules/routes for second interface to send/receive
packets that is configured by amazon ec2net utility, see a ec2net clone for
ubuntu https://github.com/ademaria/ubuntu-ec2net, so it is going to be
tricky once the second interface is bound to igb_uio. how is the dpdk<#>
interface working with   amazon ec2net utility and how mTCP going to
send/receive packet  based on the route/rules AWS allowed.

my initial trial test shows that dpdk<#> must have non 0 MAC address for
amazon ec2net utility to work,  which my indirect workaround patch could
work around it, but I have not proceeded further after that, so no success
story here so far :)

**Comment by vincentmli** [comment]
do you want the patch that user can use ifconfig command to add MAC address to dpdk<#> manually after binding the port to igb_uio? if so I can send pull request to you

**Comment by vincentmli** [comment]
I created a pull request, here it is https://github.com/eunyoung14/mtcp/pull/80

**Comment by ajamshed** [comment]
Thanks. I have merged the pull request.

**Comment by vincentmli** [comment]
I tested with above merged patch to configure the MAC manually and I am able to see packet send/receive fine between VM with SR-IOV pass through mode and another  Physical server (still not tested in AWS environment). the  should be a good workaround to support mTCP in virtual environment to resolve the MAC 00:00:00:00:00:00:00 issue

**Comment by ajamshed** [comment]
Sounds good!
