### ISSUE TITLE
Invalid acknowledgment number when responding to retransmitted SYN.

### ISSUE THREAD

**Issue by marqs85** [eunyoung14/mtcp#78]
When SYN/ACK is lost and session initiator resends SYN, receiver responds with SYN/ACK that has invalid sequence number as shown in the following capture (2nd packet gets lost).

![syn_ack_prob](https://cloud.githubusercontent.com/assets/2318351/16148176/974d2aee-3490-11e6-8689-c281e4edc850.png)

**Comment by ajamshed** [comment]
Thanks for catching the bug. I have merged the pull request.
