### ISSUE TITLE
SYN Flood protection

### ISSUE THREAD

**Issue by beHuddle** [eunyoung14/mtcp#8]
Hi,

I was browsing the source code, and I don't see any SYN Flood protection code. Maybe I missed it.
What are some security measures implemented in mtcp?

Thanks,

Lawrence

**Comment by eunyoung14** [comment]
Hi Lawrence,

mTCP does not implement SYN flood protection like syn cookies.
However, we do adopt the techniques such as delaying socket buffer allocation until the actual payload arrives.
Allocating tcb in mtcp is also very lightweight.
