### ISSUE TITLE
lighttpd run with error Abortion

### ISSUE THREAD

**Issue by RocCheng627** [eunyoung14/mtcp#83]
I compile lighttpd with code mtcp-master, every time I run the lighttpd program, there is an error:
![error](https://cloud.githubusercontent.com/assets/20167553/16380488/f3057ce4-3ca9-11e6-9e1e-0dc390b153e2.png)
I've tried my dpdk0 device by PING command, It work well.Did I missed something?

**Comment by ajamshed** [comment]
MAC address 00:00:00:00:00:00 indicates that the igb_uio driver was unable to identify dpdk-registered interface. Please double check whether you have followed all the instructions in the README file. Also, see if your interface is supported: (http://www.dpdk.org/doc/nics).

**Comment by RocCheng627** [comment]
I check the network device with dpdk_nic_bind.py, it was listed on (http://www.dpdk.org/doc/nics). Here is the infomation about my network device
![device](https://cloud.githubusercontent.com/assets/20167553/16407403/1be50728-3d46-11e6-89f4-cde97c34192c.png)
the Intel network device list as below
![intel](https://cloud.githubusercontent.com/assets/20167553/16407444/4f31f5b4-3d46-11e6-9b5a-5582df5ecb97.png)
By the way, I used VMWare with Centos7.2 OS, the network deivce is virtual device.

**Comment by ajamshed** [comment]
We have not yet officially extended mTCP stack to virtualized environments. Can you please try your setup on non-virtualised environments?

**Comment by RocCheng627** [comment]
OK, I will have a try. Thanks.

**Comment by vincentmli** [comment]
I think RocCheng627 is using Intel 82545EM, not in virtual environment, correct? you can manually use ifconfig command to add MAC to the dpdk0 interface, something like:

#ifconfig dpdk0 hw ether <MAC address>

regarding lighttpd core dump, could you run lighttpd with gdb to get the stack trace?

something like:

gdb --args <path-to-lighttpd> ....options...
(gdb) run
(gdb) bt
