### ISSUE TITLE
Get only one accepting event when handling simultaneously incomming connections from the same machine

### ISSUE THREAD

**Issue by duoh** [eunyoung14/mtcp#84]
Hello,

I find that when there are simultaneously incoming connections, mtcp_epoll_wait returns only one accepting event and the rest are quiet(other events like reading, writing are fine). However the log shown in console can detect all connections.
Do you have any idea? How can I turn on relevant logs so that I can investigate?

Regards,
Wiriyang

**Comment by ajamshed** [comment]
Is there a way you can share details about your setup? Which applications were your using and what were the connection parameters? 

In mtcp/src/Makefile there are a bunch of debugging macros that are disabled by default. You can probably re-enable them and see traffic activity logs in more detail.

**Comment by duoh** [comment]
Hello,

Thanks for your response.
Here is my app config files.
io = dpdk
num_cores = 16
num_mem_ch = 4
port = dpdk0
max_concurrency = 10000
max_num_buffers = 10000
rcvbuf = 4096
sndbuf = 4096
tcp_timeout = -1
tcp_timewait = 0
stat_print = dpdk0
The rest not shown are commented out(default)

Also, could you give me what flag I should turn on such as EPOLL and what else?

Thanks so much,
Wiriyang

**Comment by vincentmli** [comment]
I would try:

DBG_OPT = -DDBGMSG -DDBGFUNC -DSTREAM -DSTATE -DTSTAT -DAPP -DEPOLL
GCC_OPT += -DNDEBUG -O3 -DNETSTAT -DINFO -DDBGERR -DDBGCERR

**Comment by ajamshed** [comment]
Apologies for the delayed response. I notice that you have set-up 20 queues but you are using only 16 cores. This mismatch may cause problems. mTCP core assumes that num_cores == num_queues. Also, mTCP core has an ugly restriction that you can only use first 16 cores (MAX_CPUS macro is set to 16 in mtcp.h). I plan to remove this restriction in the future (hint: igb_uio.h also needs to be updated)

**Comment by duoh** [comment]
@vincentmli , thanks for your suggestion.
@ajamshed , I will change the magic number on those mentioned files.

Thanks both of you :D

**Comment by duoh** [comment]
The issue seems to be solved by make the magic number in the above-mentioned files to be identical including app config file.
