### ISSUE TITLE
Can I use MTCP for l3fwd

### ISSUE THREAD

**Issue by tigerjibo** [eunyoung14/mtcp#85]
Hi : 
  For now, I want to use MTCP + DPDK for l3fwd. Is there any function to support MTCP for l3fwd? If no, can you tell me the start point to realize this function.
  Thanks for your reply in advance.

**Comment by ajamshed** [comment]
I am not sure what's the point of running an mTCP stack below l3fwd. dpdk's l3fwd application can be used for forwarding IP traffic. mTCP stack can be used to develop TCP endpoint applications. Am I missing something here?

**Comment by tigerjibo** [comment]
Hi ajamshed :
   First,I'm sorry to reply you so late. 
   Does the mtcp stack support Routing and commands for adding, deleting, showing static route?
    Thanks for your relpy in advance!

**Comment by ajamshed** [comment]
Not yet. It is in the [TODOs](https://github.com/eunyoung14/mtcp/wiki/Supported-Features) list.

**Comment by tigerjibo** [comment]
Thank for your reply!
