### ISSUE TITLE
error in TRACE_EPOLL

### ISSUE THREAD

**Issue by yulintao** [eunyoung14/mtcp#88]
hi,mtcp
  there is a error in 	"mtcp/src/eventpll.c+130"
  TRACE_EPOLL("epoll structure of size %d created.\n", ep->size);there is no member "size" in mtcp_epoll struct

**Comment by ajamshed** [comment]
Hi,

Thanks for pointing out the problem. Can you please update line 130 with:
`TRACE_EPOLL("epoll structure of size %u created.\n", sizeof(*ep));`

I will fix this line in my next commit. Alternatively, you can send a pull request to me. I will merge your request thereafter.

**Comment by yulintao** [comment]
OK
