### ISSUE TITLE
No route to 10.10.10.222 from epwget

### ISSUE THREAD

**Issue by kcmohanprasad** [eunyoung14/mtcp#9]
Hi,

I am getting No route to epserver in epwget client. I am using the below route.conf and arp.conf. Please do let know of I have done anything wrong
route.conf
===========================================
ROUTES 1
10.10.10.222/32 port0

arp.conf
======================================
ARP_ENTRY 1
10.10.10.222/32  00:0c:29:74:12:9a

This is the error in epwget client
=======================================
[mtcp_create_context:1352] CPU 0 is in charge of printing stats.
[GetOutputInterface:  28] [WARNING] No route to 10.10.10.222
CPU 1: initialization finished.
[GetOutputInterface:  28] [WARNING] No route to 10.10.10.222
Thread 1 handles 5000 flows. connecting to 10.10.10.222:80
[GetOutputInterface:  28] [WARNING] No route to 10.10.10.222

Thanks,
Mohan

**Comment by ajamshed** [comment]
This question was answered via email.

**Comment by wtao0221** [comment]
How to solve it? Could you please share it with us?

Thanks,
Tao

**Comment by Fierralin** [comment]
I cannot find this issue's maillist. What should I do? I meet this problem too.

**Comment by ajamshed** [comment]
Can you please post your interface settings here (for both sides)?
Client & Server (both):
IP addresses?
arp.conf entries?
route.conf entries?

**Comment by Fierralin** [comment]
I finally found that the two machines was not connected together. I have to config IB net firstly. 
Thanks, 
Fierralin

**Comment by apassi99** [comment]
Hey facing the same issue. I tried running 
1) ./epwget 10.0.0.43/example.txt 10000000 -N 8 -c 8000 
2) ./epwget http://i.imgur.com/mgyXgnv.png 10000000 -N 8 -c 8000

For 1) I believe 10.0.0.43 is not hosted any more as I couldn't ping that IP either?

and 2) I get this error -

Configuration updated by mtcp_setconf().
[dpdk_init_handle: 211] Can't open /dev/dpdk-iface for context->cpu: 4! Are you using mlx4/mlx5 driver?
CPU 4: initialization finished.
[mtcp_create_context:1200] CPU 4 is now the master thread.
[GetOutputInterface:  28] [WARNING] No route to 255.255.255.255
[dpdk_init_handle: 211] Can't open /dev/dpdk-iface for context->cpu: 5! Are you using mlx4/mlx5 driver?
CPU 5: initialization finished.
[GetOutputInterface:  28] [WARNING] No route to 255.255.255.255
Thread 4 handles 1250000 flows. connecting to 255.255.255.255:80
[dpdk_init_handle: 211] Can't open /dev/dpdk-iface for context->cpu: 6! Are you using mlx4/mlx5 driver?
CPU 6: initialization finished.
[GetOutputInterface:  28] [WARNING] No route to 255.255.255.255
[GetOutputInterface:  28] [WARNING] No route to 255.255.255.255
[GetOutputInterface:  28] [WARNING] No route to 255.255.255.255
[GetOutputInterface:  28] [WARNING] No route to 255.255.255.255

I am new to this so don't really know how to search for solutions myself (so apologies about that)

**Comment by ajamshed** [comment]
Did you follow all the steps mentioned in the README file? In the README file, we are assuming that both client and server machines lie in the same LAN. I suspect that you have not set up the dpdk driver correctly.

**Comment by apassi99** [comment]
Hey Thanks for your response! I think I have the dpdk driver correctly setup as I can run the sample applications in the /example of the dpdk directory. So I guess I have to run a local server on the same LAN and perform the ewget request on that.

**Comment by apassi99** [comment]
Hey Jamshed, Can we run the client and the server on the same machine? There seems to be an error when reserving memory. 

AL: memzone_reserve_aligned_thread_unsafe(): memzone <RG_MP_mbuf_pool-0> already exists
RING: Cannot reserve memory
EAL: Error - exiting with code: 1
  Cause: Cannot init mbuf pool, errno: 17

**Comment by ajamshed** [comment]
No. Unfortunately that won't be possible. Although you can use virtual machines to run dpdk-based processes in the same machine, mTCP has not officially been extended to support virtualization. I'm afraid you will have to use 2 physical machines for mTCP communication for the time being.

**Comment by apassi99** [comment]
Thanks again for your response! One other clarification (apologies if I couldn't find it in the README file), is it possible to have a mTCP server running on same machine and have client in python that doesn't use mTCP stack? or vice versa? I was having issues in making that setup.

**Comment by ajamshed** [comment]
No. That is also not possible with mTCP. Please note that the mTCP-dpdk stack directly reads network traffic from the wire. You can probably try using netmap driver (that mTCP supports) for your set-up. You may be able to communicate between the client and the server using netmap pipe/vale interface. You may have to do a little bit of hacking inside the mTCP stack to make it work (maybe small patch-work`netmap_module.c` and `core.c` files).
