### ISSUE TITLE
mtcp_getsockopt some issues

### ISSUE THREAD

**Issue by yulintao** [eunyoung14/mtcp#93]
hi, ajamshed 

why "mtcp_getsockopt" return value is not same with official?

there is "getsockopt" return value:
On success, zero is returned.  On error, -1 is returned, and errno is set appropriately

but in mtcp ,it's not . It should be like following:
https://github.com/yulintao/mtcp/commit/1af55bbecf260d114b56f21fd50d4acd9888f63b

**Comment by ajamshed** [comment]
Yulintao, I think the return values are fine. Please note that the optname for the cases when `mtcp_getsockopt(..)` is returning 0 is `SO_ERROR` only. This means that the socket function already failed in a previous function and a `getsockopt()` function with `SO_ERROR` is called to retrieve the error number. Please see this as one possible example where `SO_ERROR` is used: http://www.linuxquestions.org/questions/programming-9/so_error-functionality-665681/

**Comment by yulintao** [comment]
`#ifdef USE_MTCP
		if ((ret = mtcp_getsockopt(mctx,c->fd, SOL_SOCKET, SO_ERROR, (void *) &err, &len))
				== -1)
#else

        if (getsockopt(c->fd, SOL_SOCKET, SO_ERROR, (void *) &err, &len)
            == -1)
#endif
        {
            err = ngx_socket_errno;
        }

        if (err) {
            c->log->action = "connecting to upstream";
            (void) ngx_connection_error(c, err, "connect(0) failed");
            return NGX_ERROR;
        }
`

above code is in function“ngx_http_upstream_test_connect” from Nginx, this return value is always -1, but in mtcp "GetSocketError" cur_stream->state is TCP_ST_ESTABLISHED .It does not look correct.

**Comment by ajamshed** [comment]
Hi Yulintao,

I am not sure I followed you completely. Can you try running the following piece of code. getsockopt() returns 0 in the following case. Let me know if I am making any mistake.

```
#include <stdlib.h>
#include <stdio.h>
#include <arpa/inet.h>

int
main(int argc , char **argv)
{
	int sock, rc;
	socklen_t optlen;
	struct sockaddr_in server;
	unsigned char optval;
     
	/* create socket */
	sock = socket(AF_INET , SOCK_STREAM , 0);
	if (sock == -1) {
		printf("Could not create socket");
		exit(EXIT_FAILURE);
	}
	
	server.sin_addr.s_addr = inet_addr("127.0.0.1");
	server.sin_family = AF_INET;
	server.sin_port = htons(6666);

	/* Try connecting to an arbitrary closed port */
	connect(sock , (struct sockaddr *)&server , sizeof(server));

	rc = getsockopt(sock, SOL_SOCKET, SO_ERROR,
			&optval, &optlen);

	fprintf(stderr, "rc returns: %d, optval is: %d, optlen is: %d\n",
		rc, optval, optlen);
     
	return EXIT_SUCCESS;
}
```

**Comment by yulintao** [comment]
With your code above the return value is:
> rc returns: 0, optval is: 0, optlen is: 0 
> - 

and I have rewrite this with mtcp,the code is like below:
```
#include <stdlib.h>
#include <stdio.h>
#include <arpa/inet.h>
#include <mtcp_api.h>
int
main(int argc , char **argv)
{
	int sock, rc;
	socklen_t optlen;
	struct sockaddr_in server;
	unsigned char optval;
	struct mtcp_conf mcfg;
	mctx_t mctx;


	mtcp_getconf(&mcfg);
	mcfg.num_cores = 1;
	mtcp_setconf(&mcfg);
	/*  initialize the mtcp context */
	if (mtcp_init("mtcp.conf")) {
		fprintf(stderr, "Failed to initialize mtcp\n");
		exit(0);
	}
	mtcp_getconf(&mcfg);
	mcfg.max_concurrency = mcfg.max_num_buffers = 500000;
	mtcp_setconf(&mcfg);
	mctx = mtcp_create_context(0);

	/*  create socket */
	sock = mtcp_socket(mctx,AF_INET , SOCK_STREAM , 0);
	if (sock == -1) {
		printf("Could not create socket");
		exit(EXIT_FAILURE);
	}

	server.sin_addr.s_addr = inet_addr("192.168.1.99");
	server.sin_family = AF_INET;
	server.sin_port = htons(80);

	/*  Try connecting to an arbitrary closed port */
	mtcp_connect(mctx,sock , (struct sockaddr *)&server , sizeof(server));

	rc = mtcp_getsockopt(mctx,sock, SOL_SOCKET, SO_ERROR,(void *)&optval, &optlen);
	
	fprintf(stdout, "rc returns: %d, optval is: %d, optlen is: %d\n",
			rc, optval, optlen);
}
while(1)
   sleep(10);
	return EXIT_SUCCESS;
```
And "mtcp_getsockopt" return value is:
### rc returns: -1, optval is: 0, optlen is: 0
> Configuration updated by mtcp_setconf().
> [New Thread 0x7ffff64e0700 (LWP 22973)]
> [New Thread 0x7ffff5cdf700 (LWP 22974)]
> CPU 0: initialization finished.
> [mtcp_create_context:1199] CPU 0 is now the master thread.
> Learned new arp entry.
> ARP Table:
> IP addr: 192.168.1.99, dst_hwaddr: 90:E2:BA:69:C1:48
> ---------------------------------------------------------------------------------
> rc returns: -1, optval is: 0, optlen is: 0
> -

**Comment by yulintao** [comment]
```c
inline int 
GetSocketError(socket_map_t socket, void *optval, socklen_t *optlen)
{
	tcp_stream *cur_stream;

	if (!socket->stream) {
		errno = EBADF;
		return -1;
	}

	cur_stream = socket->stream;
	/* when cur_stream->state == TCP_ST_CLOSED should return -1 but not 0   */
	if (cur_stream->state == TCP_ST_CLOSED) {
		if (cur_stream->close_reason == TCP_TIMEDOUT || 
				cur_stream->close_reason == TCP_CONN_FAIL || 
				cur_stream->close_reason == TCP_CONN_LOST) {
			*(int *)optval = ETIMEDOUT;
			*optlen = sizeof(int);

			return -1;
		}
	}

	if (cur_stream->state == TCP_ST_CLOSE_WAIT || 
			cur_stream->state == TCP_ST_CLOSED) { 
		if (cur_stream->close_reason == TCP_RESET) {
			*(int *)optval = ECONNRESET;
			*optlen = sizeof(int);

			return -1;
		}
	}

//	errno = ENOSYS;
	return 0;
}
```
### /* when cur_stream->state == TCP_ST_CLOSED should return -1 but not 0   */

**Comment by ajamshed** [comment]
Got it! Thanks for pointing out the problem. I will patch up the fix in my next commit. Apologies for the earlier confusion.

**Comment by ajamshed** [comment]
I looked at your suggested solution for `mtcp_getsockopt()`. Although your solution solves the problem for nginx.. it may cause issues for other use cases. For example, in [epwget.c](https://github.com/eunyoung14/mtcp/blob/master/apps/example/epwget.c#L633), your version of `mtcp_getsockopt()` will return error (-1)??? I think the best fix for `mtcp_getsockopt(.., SO_ERROR..)` is to return 0 for all cases where the `stream`'s `close_reason` is `NOT_CLOSED`. I hope this solves the problem. By the way, can you share me the code snippet that comes right before `mtcp_getsockopt(.., SO_ERROR,..)` in nginx code? I just want to make sure that the patch will work fine.

**Comment by ajamshed** [comment]
Also, there was a mistake that I made in the original sample code. The socket needs to be converted to non-blocking mode using `fcntl()` syscall. It may not necessarily be relevant to the SO_ERROR issue... but I just want to make the sample code snippet more similar to mTCP sockets.

**Comment by yulintao** [comment]
here is the code.
https://github.com/yulintao/mtcp/commit/ae25cf773b7d498db8707f1b20b45a6a64609124

**Comment by ajamshed** [comment]
Thanks. I will take a look.
