### ISSUE TITLE
multi-interfaces reception with mtcp

### ISSUE THREAD

**Issue by jugean2** [eunyoung14/mtcp#94]
Hi,

I would like to receive data from 200 clients on four 10Gb interfaces. Each interface receiving data from 50 clients. Each interface has its own listening socket and data coming from its clients are managed by one core. Each interface has only one reception queue.
I set up mtcp with netmap for one interface. I followed you instructions to bind the tasks created by mtcp on one core (core 2 for example). The server thread (epoll and read) is bound to the same cpu.  It works very well and I almost reach 9 Gb/s with 1.5 kB MTU.
I got problems when I tried to upgrade to two interfaces. I put port = netmap:p6p1 netmap:p6p2 in the conf file, called mtcp_init() once and created two contexts by calling mtcp_create_context(core) twice (once in each server thread, with core = 2 and core = 4). It seems like if each interface is managed by two cores : 
[netmap_init_handle:  69] Opening netmap:p6p1 with j: 0 (cpu: 4)
[netmap_init_handle:  69] Opening netmap:p6p1 with j: 0 (cpu: 2)
[netmap_init_handle:  69] Opening netmap:p6p2 with j: 1 (cpu: 2)
[netmap_init_handle:  69] Opening netmap:p6p2 with j: 1 (cpu: 4)
And connections don't work anymore. What am I doing wrong ? And is it possible to make what I've described ? Do I have to make two mtcp_init() ?

Thank you.

cheers,

Julien.

**Comment by ajamshed** [comment]
Can you please post mtcp.conf file? The current output is showing that two threads (2 & 4) are trying to access each interface. Since you have only 1 queue per NIC, your setup looks incorrect. You should probably try setting up 2 hardware queues per interface.

**Comment by jugean2** [comment]
This is the file :
############### mtcp configuration file ###############

io = netmap
# Number of memory channels per processor socket (dpdk-only)num_mem_ch = 4

port = netmap:p6p1 netmap:p6p2# Maximum concurrency per coremax_concurrency = 10000
# Maximum number of socket buffers per core# Set this to small value if there are many idle connectionsmax_num_buffers = 10000
# Receive buffer size of socketsrcvbuf = 131072
# Send buffer size of socketssndbuf = 131072
# TCP timeout seconds# (tcp_timeout = -1 can disable the timeout check)tcp_timeout = 1
# TCP timewait secondstcp_timewait = 0

stat_print = netmap:p6p2#######################################################

      De : Asim Jamshed <notifications@github.com>
 À : eunyoung14/mtcp <mtcp@noreply.github.com> 
Cc : jugean2 <jugean@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mercredi 27 juillet 2016 13h43
 Objet : Re: [eunyoung14/mtcp] multi-interfaces reception with mtcp (#94)
   
Can you please post mtcp.conf file? The current output is showing that two threads (2 & 4) are trying to access each interface. Since you have only 1 queue per NIC, your setup looks incorrect. You should probably try setting up 2 hardware queues per interface. —

**Comment by ajamshed** [comment]
It should be
``port = p6p1 p6p2``
&
``stat_print = p6p1 p6p2``

If you are using 2 interfaces, then are you trying to create 2 passive sockets? I'm afraid that is currently not possible. We need to extend the stack so that it supports multiple listening sockets. Right now we can only use 1. I suggest that you look at issue (https://github.com/eunyoung14/mtcp/issues/44) on how to extend this feature yourself.

**Comment by jugean2** [comment]
Ok, thanks, I will try with p6p1 and p6p2.I use one listening socket per context, I think it should work.
Cheers,
Julien.

**Comment by jugean2** [comment]
Still the same problem.
As interfaces are opened in loop with num_devices_attached iterations (netmap_module.c), it's normal to have several interfaces for one thread, isn't it ?
I'm trying to modify code in order to have only one interface managed by a single thread.
It works for few thousands of packets on 20 connections but a window size = 0 appears and breaks the connection.
I continue investigating.

Cheers,

Julien.

**Comment by ajamshed** [comment]
Jugean2,

Based on your initial configuration, the problem is most likely coming up due to your CPU settings. The stack assumes that mTCP threads will always spawn and affintize to cores starting with 0, 1, 2,.. n. You can adjust the CPU sequencing like 2, 3, 4, 5.. n (without skipping a core-id) by passing the right argument to `mtcp_create_context()` per thread. But if you want to skip a core (e.g. 2, 4), you will probably have to change the mTCP stack code slightly (maybe `core.c, io_module.c, netmap_module.c`).

**Comment by njnumjn** [comment]
@ajamshed 
Do you mean that :
mTCP supports one core processes packages from multi-NIC;
but mTCP does not support multi-core(one listen thread bind to one core) separately process packages from multi-NIC? e.g.

### codes

```
int main() {
    /*other codes*/
	for (i = 0; i < num_cores; ++i) {
		args[i].core = i;
		pthread_create(&app_thread[i],
				   NULL, run_server_thread, (void*)&(args[i].core))) {
		}
	}
    /*other codes*/
}

void* run_server_thread(void* arg) {
    int core = *((int*)arg);
    mtcp_core_affinitize(core);
    mtcp_create_context(core);
    /*other codes mtcp_socket... */
}
```
### mtcp.config
```
io = dpdk
num_cores = 2
port = dpdk0 dpdk1
```

**Comment by ajamshed** [comment]
At the moment, mTCP stack supports only one listening port. But it can split connection requests across multiple cores via RSS queues. I did not completely understand your question. You can probably rephrase your question if I missed anything.

**Comment by njnumjn** [comment]
Hi, @ajamshed 
My meaning is:
I have two threads, two cores, two NICs. in every thread, bind to

**Comment by njnumjn** [comment]
Hi, @ajamshed
My meaning is:
I have two threads, two cores, two NICs.
In thread1, it is bound to the core1, new mtcp context and listening socket are created, core1 receive packages from NIC1 and send packages to NIC1;
In thread2, it is bound to the core2, new mtcp context and listening socket are created, core2 receive packages from NIC2 and send packages to NIC2.
My question is: Is the situation above supported by mTCP ?

**Comment by ajamshed** [comment]
Apologies for the delay. mTCP stack, by default, will make the two mTCP threads (core 0 & core 1 threads) read from both interfaces (i.e. it expects the NIC driver to create 2 RSS queues). But I think you can easily program the current stack to follow your model. You just need to do a little bit of hacking in `core.c`, `dpdk_module.c` and your `main.c` (that contains the `while` loop) files. 

#Hint#: Initialize the NIC driver with 1 queue (`dpdk_module.c`). Use `core-id` to select which NIC you want to read the traffic from (`core.c`).
